### ISSUE TITLE
Discussion: redux-saga

### ISSUE THREAD

**Issue by chapati23** [ngrx/effects#1]
Funny to open an issue in an empty repo, i know.

But because I'm currently struggling with this I was just wondering: Where will the `effects` lib fit in within the ngrx-ecosystem? I'm guessing it will be some kind of middleware. There's probably an equivalent in the react redux world, could you point me to it? Will this be similar to https://github.com/redux-effects/redux-effects?

The reason I'm asking: At work I'm currently building a bigger React/Redux project. We're using redux-saga for our async stuff and I have to say I _love_ the clean separation between redux store and side-effects plus the simple testability of side-effects (which can get very ugly when using thunks).

P.S. Also, if this lib will be similar to something from react/redux land this raises the question for me why we don't just try unifying the ngrx-interface to be able to use _all_ existing redux-middleware vs. having to re-implement everything from scratch

**Comment by littleStudent** [comment]
I cant exactly tell you which direction this will move, but it should be fairly similar to `redux-saga`.
ngrx/effects will be able to handle side-effects for ngrx/store apps.

The learnings from [store-saga](https://github.com/CodeSequence/store-saga) will be applied here and officially supported for ngrx (i guess)

**Comment by chapati23** [comment]
as this repo isn't empty anymore (and i've since learned a bit about how ngrx differs from redux) i'll close this issue
