### ISSUE TITLE
Optional Effect dispatch

### ISSUE THREAD

**Issue by vik-buchinski-azati** [ngrx/effects#101]
Hi everyone, it would be great to have such effects, which optionally will dispatch actions. { dispatch: false } is not for my case, because I should dispatch only if condition matched inside effect. There is my example:

@Effect() private processError$: Observable<any> = this.actions$
    .ofType(errorsAction.ActionTypes.ERROR)
    .map((action: errorsAction.ErrorsAction) => {
      if (action.payload && action.payload.errors && action.payload.errors.length > 0) {
        action.payload.errors.forEach((error) => this.alertService.error(error.message));
      }
      if (action.status === 401) {
        return new sessionAction.SessionRevokeCompleteAction({});
      }
    });

**Comment by bertofer** [comment]
In this case what I do is `{dispatch: false}` and then use `this.store.dispatch` manually

**Comment by fxck** [comment]
Just put 
```
.filter(action => !!action)
