### ISSUE TITLE
Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.

### ISSUE THREAD

**Issue by arturh85** [ngrx/effects#106]
When upgrading to angular 4.0.0-rc2 the following error is thrown when building a minimal angular application with ngrx effects: 

```
[at-loader] Checking finished with 1 errors
Error in bail mode: [at-loader] compiled\node_modules\@ngrx\effects\src\effects.module.ngfactory.ts:33:67
    TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
  Types of property 'next' are incompatible.
    Type '(action: Action) => void' is not assignable to type '(value: Actions) => void'.
      Types of parameters 'action' and 'value' are incompatible.
        Type 'Actions' is not assignable to type 'Action'.
          Property 'type' is missing in type 'Actions'.
```

This can be reproduced with the following commands:

```
git clone https://github.com/arturh85/angular2-webpack-starter.git
cd angular2-webpack-starter
npm i
npm run build:prod
```

**Comment by nosachamos** [comment]
Also getting this.

**Comment by arturh85** [comment]
It looks to me like the open pull request fixed this issue, please merge: https://github.com/ngrx/effects/pull/97

**Comment by arturh85** [comment]
eh, reopening until merged...

**Comment by gregbown** [comment]
TypeScript 2.2.1
Angular 4.0.0-rc.2
Effects 2.0.0
Store 2.2.1
    TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
  Types of property 'next' are incompatible.
    Type '(action: Action) => void' is not assignable to type '(value: Actions) => void'.
      Types of parameters 'action' and 'value' are incompatible.
        Type 'Actions' is not assignable to type 'Action'.
          Property 'type' is missing in type '**Actions**'.

**Comment by littleStudent** [comment]
I have the exact same setup, but no problems with AOT.
I am using the cli 1.0.0-rc.0 though for building.

**Comment by karolmie1** [comment]
@littleStudent maybe you have more lax tsconfig settings? I've build my app from fork with patch, and I've noticed more problems: with new angular4 compiler effects cannot be build with "noImplicitAny: true" setting. I think this too should be addressed.

```
'lift' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
Error at @ngrx/effects/src/actions.ts:16:8: Parameter 'operator' implicitly has an 'any' type.
Error at @ngrx/effects/src/actions.ts:17:11: 'observable' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
Error at @ngrx/effects/src/actions.ts:23:33: Binding element 'type' implicitly has an 'any' type.
    at new UserError (@angular/tsc-wrapped/src/tsc.ts:33:25)
    at check (@angular/tsc-wrapped/src/tsc.ts:69:11)
    at Tsc.typeCheck (@angular/tsc-wrapped/src/tsc.ts:152:5)
    at @angular/tsc-wrapped/src/main.ts:68:11
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by arturh85** [comment]
@littleStudent I'm confused, how do you have the exact same setup if you are using angular cli instead? additionally the problem described here also happens in normal builds without AOT

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/effects/pull/97

**Comment by Elecash** [comment]
Updating to @ngrx/effects v2.0.2 fixes this problem.

**Comment by vredchenko** [comment]
FYI I'm getting this issue with `@ngrx/effects v2.0.3`

**Comment by Manojmahajan119** [comment]
i have update the angular4  into angular 5 and also update libray ngrx into latest version ngrx4 but during run the code i have got the error related to payload does not exist in action. how to fixed it.?
Error------
ERROR in C:/Users/seefat/studio-lite-master/src/app/location/location-map.ts (303,57): Argument of type '{ type: string; payload: IUiState; }' is not assignable to parameter of type 'Action'.
  Object literal may only specify known properties, and 'payload' does not exist in type 'Action'.

ERROR in C:/Users/seefat/studio-lite-master/src/app/location/location-map.ts (316,57): Argument of type '{ type: string; payload: IUiState; }' is not assignable to parameter of type 'Action'.
  Object literal may only specify known properties, and 'payload' does not exist in type 'Action'.

**Comment by nosachamos** [comment]
@Manojmahajan119 payload has been removed from the Action interface. See here for why that happened and a simple workaround if you need it (most of us do, for some actions):

https://github.com/ngrx/platform/issues/31

**Comment by phpcodexpert** [comment]
Hi nosachamos  
i have an issue with using ngrx4 when i have working with less version of ngrx then work properly. how to resolve the issue related to :   Object literal may only specify known properties, and 'payload' does not exist in type 'Action'.
angular 5 support ngrx4 or not?

**Comment by phpcodexpert** [comment]
![screenshot 3](https://user-images.githubusercontent.com/29730750/32776559-f580edf4-c958-11e7-8cb0-772c9ab9cb42.png)

how we fix it
