### ISSUE TITLE
subscription.addEffects([]) removes existing effects on the subscription.

### ISSUE THREAD

**Issue by akilabala** [ngrx/effects#109]
I have a function in a shared utility module that registers reducers and effects:

@Injectable()
export class ReducerManager {
  private reducers: any = {};

  constructor(private store: Store<any>, private subscription: EffectsSubscription) {}

  addReducerEffects(name: string, reducers: Function, effects: any[]) {
    if (this.reducers[name] === undefined) {
      this.reducers[name] = reducers;
      this.store.replaceReducer(combineReducers(this.reducers));
      this.subscription.addEffects(effects);
    }
  }

}

I have 2 lazily loaded modules. One of the modules adds an instance of effects class to the subscription:

reducerManager.addReducerEffects('finPlan', finPlanReducer, [finPlanEffects]);

Another lazy loaded module has no effects, so it just registers its reducer function alone and passes an empty array for effects:

reducerManager.addReducerEffects('person', personReducer, []);

subscription.addEffects([]) removes previously added effects.

**Comment by akilabala** [comment]
I have currently prevented this by doing a length check inside my function:

addReducerEffects(name: string, reducers: Function, effects: any[]) {

    if (this.reducers[name] === undefined) {
      this.reducers[name] = reducers;
      this.store.replaceReducer(combineReducers(this.reducers));

      **if (effects.length > 0)** {
        this.sub.addEffects(effects);
      }
    }

  }

**Comment by robwormald** [comment]
This should be fixed and implemented. Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
