### ISSUE TITLE
Angular 4 rc5 breaks ngrx/effects 2.0.0

### ISSUE THREAD

**Issue by robertohuertasm** [ngrx/effects#113]
With [this breaking change](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes) the library is not reliable anymore.

When you subscribe to the same action in different effects only the first one is executed. In fact, this is not always consistent. If the first effect doesn't return any action, makes an external ajax request before returning it or you use a `setTimeout` then the second subscription will be executed.

I've prepared a [small sample app](https://github.com/robertohuertasm/ngrx-effects-broken) with 2 branches (one with the `rc5` - master - and another with `rc3`) so you can take a look at it. This is a very simple project which dispatches an action when the app starts and has two effects associated to it.

With the `rc5` version only the first subscription will run. With the `rc3` it will work as expected.

I've tried to inject the effect service into the component and into the module but still it doesn't seem to force an eager loading.

**Comment by MikeRyan52** [comment]
Solution is to inject the `EffectsSubscription` class into the Effects module here: https://github.com/ngrx/effects/blob/master/src/effects.module.ts#L19

**Comment by robertohuertasm** [comment]
Hi @MikeRyan52, is there any expected date when this will be published?

**Comment by MikeRyan52** [comment]
Released in v2.0.1. Thanks @robertohuertasm!
