### ISSUE TITLE
Using version `2.0.1` breaking AOT

### ISSUE THREAD

**Issue by pfrendo** [ngrx/effects#115]
Using version `2.0.1` breaking AOT.

Error when generating AOT build:  "Can't resolve ./bootstrap-listener from "node_modules/@ngrx/effects/src/effects.module.d.ts" Error: Cannot read property 'runAfterBootstrapEffects' of undefined, resolving symbol EffectsModule in "node_modules/@ngrx/effects" EffectsModule...

Most probably because of this change:

https://github.com/ngrx/effects/commit/3cf1e0e

**Comment by MikeRyan52** [comment]
Released in v2.0.2
