### ISSUE TITLE
Q: when should I use EffectsSubscription?

### ISSUE THREAD

**Issue by StevenLiekens** [ngrx/effects#117]
The API reference shows an example of manually unsubscribing from effects.

```ts
class MyComponent {
  constructor(private subscription: EffectsSubscription) { }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```

Can someone give an example of when this is useful? Also, is it ever necessary to write code like this?

**Comment by pfrendo** [comment]
I think the only place it's really useful is when you want to stop side effects from firing

**Comment by StevenLiekens** [comment]
Does anyone have a real world example of this?

**Comment by StevenLiekens** [comment]
I think I have a use case for EffectsSubscription.

My app has many different types of LOAD actions for many different slices of state. A change to one slice of state can invalidate all the other slices of state. User management is a typical crosscutting concern that has this effect on an application. When a user logs in, there are many views that need to be updated to display the data for the user.

In terms of ngrx effects:
when action is of type USER_LOGON, dispatch LOAD_A, dispatch LOAD_B, dispatch LOAD_C, ..., dispatch LOAD_Z.

My problem with this is that I don't want to load all the data as soon as the user logs on. Instead, I want to dispatch only the load actions for data that is required by components on the current route.

My solution to this problem right now is to let components be in charge of when to dispatch load actions. When components are destroyed, they stop dispatching load actions. This ensures that data is not loaded until it's really needed.

Instead, I'd like to let ngrx effects dispatch load actions when a user logs on, but ONLY for data that is really needed on the current route.

Is this something that I can accomplish by manually subscribing/unsubscribing from effects?

**Comment by StevenLiekens** [comment]
@MikeRyanDev what do you mean by fixed in 4.0? I was just asking for more information / example code.

**Comment by MikeRyanDev** [comment]
@StevenLiekens Sorry, I was labelling issues that will not be relevant in 4.0 or were fixed. The EffectsSubscription class has been removed and there's a much better API for controlling when an effect is running or not.

**Comment by StevenLiekens** [comment]
Cool. Is it already documented somewhere?
