### ISSUE TITLE
[Bug] Effects services doesn't instantiate when lazy-loaded with Angular 4.0.0 final

### ISSUE THREAD

**Issue by guojenman** [ngrx/effects#118]
Can not lazy load @ngrx/effects 2.0.0 with angular 4.0.0. 

with angular 4.0.0-rc.3 - works - see "EffectsService created" logged in the console
http://plnkr.co/edit/UIeApeiohZWRxmr5yApV?p=preview

with angular 4.0.0 final - does not work - "EffectsService created" is NOT logged in the console
http://plnkr.co/edit/xnFNQvNjW3FrDV3jcFfs?p=preview

**Comment by MikeRyan52** [comment]
Upgrading your plnkr to effects v2.0.2 seemed to fix the problem. Can you verify that the latest release works in your app?

**Comment by guojenman** [comment]
@MikeRyan52  Thanks, though I'm seeing another error after this but I haven't been able to isolate it in a minimal reproducible example yet. I'll try to isolate it in a minimal reproducible example and report back. 

fyi, this is the error I'm seeing now,
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at combineReducers (utils.js:2)
```

**Comment by MikeRyan52** [comment]
@guojenman That's a separate bug with @ngrx/store-devtools.

**Comment by guojenman** [comment]
@MikeRyan52 Oh wow! you're on top of it. Thanks. I can verify that 2.0.2 works in both JIT and AoT mode after I disable store-devtools.

Should I report a bug over at store-devtools branch or do you know if they area already aware of it, it seems this was at the tip of your fingers just waiting for somebody to ask :)

Thanks for the help!

**Comment by MikeRyan52** [comment]
@guojenman I _just_ published a fix for @ngrx/store-devtools. Using latest of that package should clear the issue up.
