### ISSUE TITLE
Cyclic dependency exception when effects depends on deprecated Router

### ISSUE THREAD

**Issue by BrainCrumbz** [ngrx/effects#12]
Hello

our team is migrating just now to @ngrx/store 2.0.0 and consequently to @ngrx/effects 1.0.1, as our application was using redux-saga.

After all migration work, the only outstanding issue is that one of our `XxxxEffects` class has a dependency on `Router` from `@angular/router-deprecated`. Build goes fine, but when running in browser, console shows:

> EXCEPTION: Cannot instantiate cyclic dependency! (Token Application Initializer -> Token @ngrx/effects Bootstrap Effects -> Router -> RouteRegistry)

followed by a number of:

> EXCEPTION: Error during instantiation of ApplicationRef_! (Token Application Initializer -> Token @ngrx/effects Bootstrap Effects -> Router -> RouteRegistry -> Token RouterPrimaryComponent -> ApplicationRef -> ApplicationRef_).

Just as a proof, if we comment out that dependency from our effect class, no error is shown. Such effect needs a reference to `Router` in order to `router.navigate(...)` to some specific path when some specific action is dispatched.

Do you have any hint on how can we circumvent this cyclic dependency? 

**NOTE:** we are not using @ngrx/router. Only /core, /store, /effects and ngrx-store-logger.

**Comment by BrainCrumbz** [comment]
Uhm ... ok. It looks like we'll have to switch from *@angular/router-deprecated* to *@ngrx/router* and *@ngrx/router-store*, as the latter exposes actions to navigate to other paths.

**Comment by MikeRyan52** [comment]
`@ngrx/router-store` is to connect `@ngrx/router` and `@ngrx/store`. It wont' work with the old deprecated router.

I'm marking this as a bug and seeing if there's anyway I can fix the issue, however I do recommend taking a look at @ngrx/router. The new @angular/router will end up resembling @ngrx/router in a lot of ways.

**Comment by BrainCrumbz** [comment]
Hello! Thanks for reply and clarifying. Sorry, I think I was not clear: we did take the approach of removing completely angular2 router(s) and switching to @ngrxr `router` + `router-store`.  
We were especially interested in `router-store` (on top of `@ngrx/router`) because it exposed actions (e.g. `go()`) to navigate to other paths.

On the cyclic dependency: once we did not inject anymore angular2 deprecated router, and started using @ngrx router & router-state, we stopped seeing that error. At that point we were also able to completely remove angular2 router(s) from project dependencies altogether. 

What seems strange is that @ngrx router stuff does not seem to depend on angular2 router stuff, still the error says just that.

**Comment by benorama** [comment]
Hi, I had  a working prototype based on `ngrx/store` 2.0.0 + `ngrx/router` 1.0.0-beta.1.
I've upgraded it from angular rc1 to rc2 successfully.
Now I'm trying to replace the `ngrx/router` with the new `angular/router` 3.0.0-alpha.3, which should be based/inspired by `ngrx/store`.
But I'm also getting this error (Cyclic dependency exception) when trying to inject `router: Router` in my effects.
Any suggestion or workaround?
We will probably continue to use `ngrx/router` but I guess it is going to be deprecated since the new `angular/router` should be the way to go now?

**Comment by AliakseiBahachuk** [comment]
Hello,

I have the same issues:
'Cyclic dependency exception' after injection router-depricated {Router} in effect class.

**Comment by vincentpalita** [comment]
Hello,

got the same problem here. I am quite blocked trying to navigate inside the app with router-deprecated and I can read here that router v3 doesn't work aswell.
Do you have any updates on this @MikeRyan52? 

Thank you very much!
Vincent

**Comment by vincentpalita** [comment]
Well,

This can be done by injecting the router directly via injector.
Create a method to get the router like this:

```    
getRouter() {
        if(!this.router) {
            this.router = this.inj.get(Router);
        }
        return this.router;
    }
```

Then in the effects you can invoke it like this:

```
this.getRouter().navigate(['App', 'Index']);
```

This is an _ugly_ way to make it work, but it does the job.

**Comment by zeeshanjan82** [comment]
@vincentpalita I have tried the solution but its not working for me, if I comment out the following line in the constructor 
```js
    private router: Router,
```
then the error is gone but I get this.router undefined.

**Comment by qdouble** [comment]
I just updated to the latest angular-builds and ngModules setup and this error still exist as 
```
provider_analyzer.js:291Uncaught Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef: in NgModule MyAppModule
```
I was told before that this problem may go away in RC5, but it doesn't seem like that's going to be the case.

**Comment by astopo** [comment]
I am also having the same problem with a service that is injected with the Router. Also only using /core, /store, /effects and ngrx-store-logger. Removing the dependency resolves the error.

**Comment by drejohnson** [comment]
Thanks @vincentpalita! Your solution isn't pretty but it works with RC5.

**Comment by metanav** [comment]
It's  a blocking issue should be fixed  ASAP.

**Comment by MikeRyan52** [comment]
We're still tracking this, but as an alternative we have upgraded [ngrx/router-store](https://github.com/ngrx/router-store) to work with the new @angular/router. This will allow you to dispatch actions to update the router state rather than having to inject the `Router` service

**Comment by metanav** [comment]
@MikeRyan52 that's good. But instead of using: store.dispatch(go('/path', { query: 'string' }));
in the effects classes, can we just return an action to rediect using router-store? Actually I do not want to inject Store in effects and any actions return by effects is automagically dispatched.

**Comment by MikeRyan52** [comment]
@metanav Yes, the idea is that you would map to a router action in your effect and have it be dispatched that way.

**Comment by MikeRyan52** [comment]
Won't fix. v2.0.0 should make it easy to inject the new Router service. Thanks!

**Comment by BrainCrumbz** [comment]
Just as a ref, `runAfterBootstrap` is documented [here](https://github.com/ngrx/effects/blob/master/docs/api.md#runafterbootstrap)
