### ISSUE TITLE
Support Angular 4

### ISSUE THREAD

**Issue by rkusuma** [ngrx/effects#120]
will `ngrx/effects` support angular 4?

**Comment by alexjajones** [comment]
I seem to be getting the following issue when using Angular 4: 

`Uncaught Error: Can't resolve all parameters for EffectsSubscription: (?, ?, ?)`

Anyone have any ideas what may be causing this?

**Comment by diicar** [comment]
@rkusuma works fine for me...

**Comment by robertohuertasm** [comment]
This issue should be closed @rkusuma

**Comment by m-abs** [comment]
npm complains about peerDependencies with angular 4, so I don't think this should be closed just yet.

**Comment by robertohuertasm** [comment]
Fair enough. Then I think the title of this issue is not specific enough because the library works with Angular 4. Anyway, I think there's a PR trying to fix this #119

**Comment by tobiasmuecksch** [comment]
@robertohuertasm Does AOT building work for you with Angular 4?

**Comment by robertohuertasm** [comment]
Yes. It doesn't for you?

**Comment by tobiasmuecksch** [comment]
Well. I'm still struggling with upgrading to angular 4. I am asking, so I can rule out ngrx/effects as problem source. Thank you you for that ;-)

**Comment by kuncevic** [comment]
got some issues with Angular 4 https://github.com/ngrx/effects/issues/139

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/effects/pull/142
