### ISSUE TITLE
Add effects on new store instance

### ISSUE THREAD

**Issue by denkomanceski** [ngrx/effects#121]
Hi, I needed to create multiple instances of my app so I have provideStore(reducers) inside of some parent component (which is not the root or the one used for bootstrapping the app). 
That means that below that component I will have a separate store.. and everything works fine.. but now I have a problem because the effects do not work when dispatching actions to this store.. How can I register the effects for this newly created store? I tried everything in the providers array, and merge, addEffects, but none of the effects are triggered on the new store.

Regards

**Comment by pfrendo** [comment]
Can you post some samples please?

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
