### ISSUE TITLE
Effects imported by multiple lazy loaded modules loaded multiple times

### ISSUE THREAD

**Issue by karptonite** [ngrx/effects#123]
Now that the https://github.com/angular/angular/issues/12869 is fixed, providers no longer always instantiate twice with lazy loading.

However, there is another related issue that still exists, I believe. If you have an effect that is used by more than one lazy loaded endpoint, it will be loaded multiple times if you go from route to route between them. 

For example, we have a tagging system, which has its own nxrx/effects. The tags are used by the images, the files, and the videos systems (each lazy loaded). 

Ideally, the tagging effects (with dependencies) would only be loaded for these particular pages. However, if they are loaded in the `imports` section of each lazy-loaded module, they are instantiated each time the user uses a `routerLink` to jump from one type to another. That means that the effects are dispatched more than once if the user has visited different sorts of pages.

Of course, we could solve this by importing any effects that are needed for multiple lazy loaded modules in the root app module, or in some module imported by the app module. But that is obviously not ideal from a lazy loading perspective, since we don't need tags on all pages, just a small subset of them. 

I'm not sure of the best solution for this--here are a couple of naive suggestions, though. One option, though, would be to change EffectsModule.run so that it skips Effects classes that have been previously imported. Another option would be to somehow limit the effects that run on a lazy-loaded route to those that were imported and run by the lazy loaded module or the AppModule. That would mean that if a user starts on a file page, and imports the Tag effects, then switches to the image page, the image page module would also import its own instance of the Tag effects, but the Tag effects previously imported in "files" would be inactive. 

I don't know enough about Angular internals or how ngrx/effects works to know if either of these are workable solutions.

**Comment by sickelap** [comment]
Just came across repo where effects are implemented in lazy modules [FabienDehopre/ngrx-lazy-load](https://github.com/FabienDehopre/ngrx-lazy-load). IMO approach is little sketchy because it uses global `effectsAdded` for caching effect subscriptions. But that's the best solution I've found so far.

**Comment by monospaced** [comment]
I am also experiencing this issue, I don't think it's limited to effects imported by multiple lazy loaded modules? 

For me, even an effect imported by a single lazy loaded module, will be loaded again every time that route is hit.

**Comment by karptonite** [comment]
@monospaced, are you on Angular 4 yet? What you describe happened with Angular 2, but has been fixed in the newest version.

**Comment by monospaced** [comment]
@karptonite Yes, still on Angular 2. Will try upgrading and report back 👍

**Comment by elwynelwyn** [comment]
Our attempt at getting around this problem:

Every module that has effects uses a new helper to provide the effects:
```
@NgModule({
    imports: [
        SomeImport
    ]
})
export class FeatureModule {
    public static withEffects(): ModuleWithProviders {
        return {
            ngModule: FeatureModule,
            providers: [
                addEffectOnce(MyCoolEffects)
            ]
        };
    }
}
```

Then when importing this module, say into AppModule, or into a lazy-loaded parent module, do:
```
imports: [
    FeatureModule.withEffects()
]
```

The magic happens inside this little helper, `add-effect-once.ts`
```
import { EffectsModule } from '@ngrx/effects';

const effects = new Map<any, any>();

export function addEffectOnce (effect) {
    if (effects.has(effect)) {
        return [];
    } else {
        effects.set(effect, true);
        return EffectsModule.run(effect).providers;
    }
}
```

Pros:
Pretty simple to understand what's going on, seems to work pretty well

Cons:
Requires you to remember to call `withEffects()` on your modules, and structure your code a bit differently
Doesn't currently work with AoT, getting the classic `Error encountered resolving symbol values statically., function calls are not supported`.

**Comment by FabienDehopre** [comment]
@elwynelwyn It seems that your solution won't work with lazy loaded module since you have to call the `withEffects()` method when importing the module.

**Comment by elwynelwyn** [comment]
Yeah, in our app we are lazy loading a "parent" module which is a module for an area / page of the app, and that "parent" module pulls in the individual feature modules which call `withEffects()`.

But being able to have effects run on the lazy loaded module itself would certainly be much more flexible.

**Comment by elwynelwyn** [comment]
OK previous workaround has not been working for us ^^ so I've made a PR that builds on @FabienDehopre's repo.
@MikeRyanDev / @brandonroberts interested to hear your thoughts, and let me know if you'd rather I make the PR against the new monorepo

**Comment by elwynelwyn** [comment]
For those following along on this issue, the PR is now over at the new monorepo.

https://github.com/ngrx/platform/pull/23

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
