### ISSUE TITLE
Design interrogation on using effects as "side" ones (when relevant)

### ISSUE THREAD

**Issue by guenam** [ngrx/effects#125]
I'm writing this to know if I get it right or not.

On examples found online, the pattern usually goes like this (example here on add/delete actions on the state and on a remote database) :

effects.ts : 

    @Effect()
    add$ = this.action$
      .ofType(ADD)
      .switchMap((action: Action) => {
         return this.http.put(...)
           .map( response => response.json() )
           .map( response => Observable.of({ type: ADD_SUCCESS, payload: action.payload }))
           .catch( response => Observable.of({ type: ADD_FAIL, payload: response.status }))

reducer.ts

    ...
    switch (action.type){
      case 'ADD_SUCCESS':
         ...
         return new_state;
      case 'ADD_FAIL':
         return state;
    }

It works, **but the speed of execution as felt by the user depends on how fast the network is**. So I came up with a pattern that bets on the high probability that no error will be returned from the API:

reducer.ts

    ...
    switch (action.type){
      case 'ADD':
         ... // make the adequate addition
         return new_state;
      case 'ADD_FAIL':
         ... // delete the addition previously made
         return new_state;
    }

effects.ts : 

    @Effect()
    add$ = this.action$
      .ofType(ADD)
      .switchMap((action: Action) => {
         return this.http.put(...)
           .map( response => response.json() )
           .catch( response => Observable.of({ type: ADD_FAIL, payload: action.payload }))

In this pattern, the action of saving to database really is a "side effect". In the unlikely but possible case where the API return an error, then a second action is taken to undo the first action.

But I haven't found yet this design in the examples given online: Since I'm an amateur dev, I wonder if I missed something that makes it wrong/dangerous/inefficient in the end.

**Comment by MikeRyan52** [comment]
This pattern has a more formal name called "optimistic updates". It is a great pattern as long as you can guarantee a high degree of success for your network requests.

**Comment by guenam** [comment]
Thanks @MikeRyan52 for your quick and kind reply. As an amateur dev, I'm proud of having reinvented the wheel! ;-) More seriously, I can now go on with my project without wondering.
