### ISSUE TITLE
Effect not catching all actions

### ISSUE THREAD

**Issue by SwagStormer** [ngrx/effects#147]
Versions:
Angular: 4.0.3
ngrx core: 1.2.0
effects: 2.0.2
store: 2.2.1

**tl;dr* Effects don't instantiate fast enough

This is an effect for books,
```  
  @Effect()
  readListEffect = this.actions
    .ofType(readListAction('Book'))
    .switchMap(() => this.booksService.readList())
    .map(results => new ReadListSuccessAction(this.modelName, results));
```

This is an effect for authors,
```
  @Effect()
  readListEffect = this.actions
    .ofType(readListAction('Author))
    .switchMap(() => this.authorService.readList())
    .map(results => new ReadListSuccessAction(this.modelName, results))
```

Inside my books component constructor:
```
store.dispatch({type: readListAction('Book'});
```

and author component constructor:
```
this.store.dispatch({type: readListAction('Author')});
```

Sometimes neither of these events are caught, sometimes one before the other, etc. My guess is that the Effect isn't instantiated fast enough therefore not getting the values passed through the subscription. This can be supported by the fact doing a setTimeout() works

**Comment by bertofer** [comment]
This might me related https://github.com/ngrx/platform/issues/20

**Comment by SwagStormer** [comment]
@bertofer turns out I read the docs wrong. I was pretty sure that I saw that it needed to be EffectsModulke.runAfterBootstrap(), while what I really needed was EffectsModule.run()
