### ISSUE TITLE
Dispatch one action multiple times at once

### ISSUE THREAD

**Issue by hnguyenec** [ngrx/effects#149]
My app has 3 download buttons
Each button click will dispatch DownloadFileAction(payload=fileId)
An Effect will keep listening for Download_File_Action type 
@Effect()
  download_attachment$: Observable<Action> = this.actions$
    .ofType(FileActions.ActionTypes.DOWNLOAD_ATTACHMENT)
    .map(toPayload)
    .switchMap( attachment => {
      return this.service.downloadAttachment(attachment.link) //absolute link
        .map( (data) => {
          this.service.saveAttachment(data); //save file locally
          return new FileActions.DownloadAttachmentSuccessAction(attachment);
        })
        .catch(error => {
          //debugger;
          console.log(error);
        });
    })

If more than 1 button are clicked at the same time, 2 DownloadFileAction actions will be dispatched

Howerver, download_attachment$ effect only listen for one which is downloaded first and then return DownloadAttachmentSuccessAction, thus the other downloading files will not be finished

Is there any solution or workaround ?
Your idea is much appreciated

**Comment by kylecordes** [comment]
Looking at the code, it appears to me that `switchMap` and Effects in general are likely working as designed. `switchMap` is canceling your earlier requests in progress and allowing only the last to succeed. For the use case you describe, you probably want `mergeMap` instead.

**Comment by hnguyenec** [comment]
Thanks kylecordes, mergeMap works
