### ISSUE TITLE
runEffects() should work in component providers

### ISSUE THREAD

**Issue by mb-jenks** [ngrx/effects#15]
why doesn't `runEffects()` work in a component's provider?  It seems as if the angular2 team is pushing away from calling providers from within Bootstrap and instead use the app component but runEffects does not work in that setup.

**Comment by MikeRyan52** [comment]
`runEffects()` binds to the `APP_INITIALIZER` token in order to connect the effects to the dispatcher. There is no equivalent API for when components are initialized.

**Comment by denkomanceski** [comment]
So, what is the best way to initialize effects in providers: [] ? I needed multiple instances of the store, so I used provideStore(reducers) inside of the providers: [] and it works just fine, but the effects are not run (because they are not registered for that new store)..
