### ISSUE TITLE
Misunderstanding of catch logic

### ISSUE THREAD

**Issue by prostoandrei** [ngrx/effects#158]
Hello!

I saw a lot of issue about Effects stopping after `.catch`.
Can you provide some TRUE way to handle this?

I solved all my problems about it in my code, but I have some feelings that it can be better.

Here is example:

Some method to dispatch action:
```
onSubmit(form: NgForm, e: Event) {
    e.preventDefault();

    if (form.valid) {
      const { email, password } = form.value;
      this.store.dispatch({
        type: ActionTypes.LOGIN,
        payload: { email, password }
      });
    }
  }
```

Then my effect:
```
@Effect() login$ = this.actions$
    .ofType(ActionTypes.LOGIN)
    .switchMap(({ payload }) => this.auth.authorize(payload.email, payload.password))
    .map((res) => {
      this.token.setToken(res);
      this.store.dispatch(go(['/home']));
      return { type: ActionTypes.LOGIN_SUCCESS };
    })
    .catch((err) => {
      return Observable.of({ type: ActionTypes.LOGIN_ERROR, payload: err });
    });
```
On switch map we have a method `this.auth.authorize(payload.email, payload.password)` and if we have an error (auth error for example) it's enter to `.catch` block in effect. But it stopped it

Should I handle error in `authorize` `.catch` method and send it to `.map` in my effects? It does not look as proper way, because authorize should return one type of data but I must send another if I have an error.
Of course I can add some If in .map but it looks like a hack.
I want to handle error in catch (it looks clearer)

**Comment by dlegatt** [comment]
Look at this example:
` @Effect() login$ = this.actions$
      // Listen for the 'LOGIN' action
      .ofType('LOGIN')
      // Map the payload into JSON to use as the request body
      .map(action => JSON.stringify(action.payload))
      .switchMap(payload => this.http.post('/auth', payload)
        // If successful, dispatch success action with result
        .map(res => ({ type: 'LOGIN_SUCCESS', payload: res.json() }))
        // If request fails, dispatch failed action
        .catch(() => Observable.of({ type: 'LOGIN_FAILED' }))
      );
}`

The `.map` and `.catch` operators are both running off of the service call, not the `.switchMap`.  In this example, the call is directly to the Http service, but in my code, call my service which returns an Http post and it works just fine without preventing future effects from running.

**Comment by prostoandrei** [comment]
@dlegatt thank you, but I tried this.

Method `authorize` looks like this:
```
authorize(login: string, password: string): Observable<TokenObject> {
    return this.token
      .getSessionId(login, password)
        .switchMap(res => this.token.getOauthCode(res.sessionId))
        .switchMap(res => this.token.getNewToken(res.code))
        .map(token => token)
        .catch(err => Observable.throw(err));
  }
```

So when I catch error in `getSesstionId` I throw it upper in `LoginEffects` where I'm catching it and send it to Effects like above:
```
.catch((err) => {
  return Observable.of({ type: ActionTypes.LOGIN_ERROR, payload: err });
});
```
But this stopped effects anyway.

But `.catch(err => Observable.empty());` works fine.

**Comment by alex-okrushko** [comment]
That's actually not the effects issue, but the way Observables work. @dlegatt has the right solution. Custom operator might work as well.

**Comment by prostoandrei** [comment]
Ok. Thank you everyone.
