### ISSUE TITLE
Effects are not chained in tests

### ISSUE THREAD

**Issue by ajcrites** [ngrx/effects#159]
I have an effect that looks like

    @Effect()
    add$ = this.actions$.ofType(ADD).switchMap(() => ({ type: ADD_COMPLETE }));

    @Effect()
    addComplete$ = this.actions$.ofType(ADD_COMPLETE).switchMap(() => ({ type: TOGGLE }));

This chain of side effects works as expected in the app, but it does not work in tests.

     runner.queue({ type: ADD });    

     effects.addComplete$.subscribe(result => {
       // This never seems to be called
       expect(result).toEqual({ type: TOGGLE });
     });

     effects.add$.subscribe(result => {
       // Passes, as expected
       expect(result).toEqual({ type: ADD_COMPLETE });
     });

**Comment by gallagherrchris** [comment]
You are manually calling subscribe on `add$` therefore the result will never be added to the queue.

If you change your test for `add$` to be like this, it should work

```
effects.add$.subscribe(result => {
  // Passes, as expected
  expect(result).toEqual({ type: ADD_COMPLETE });
  runner.queue(result);
}
```

Additionally, you don't need `switchMap` if you aren't changing the observable stream, regular `map` will work fine.

**Comment by ajcrites** [comment]
@gallagherrchris thanks, I'll try this out.

If I just used `map` wouldn't I have to return an observable wrapping the action, for instance using `of`?

**Comment by gallagherrchris** [comment]
@ajcrites when you use `map` you are still inside the Observable, so there is no need to create a new one.  If you did, you would actually return `Observable<Observable<Action>>` which you don't want.

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
