### ISSUE TITLE
Code Coverage Question

### ISSUE THREAD

**Issue by PhillipZada** [ngrx/effects#160]
Hi all,

I've built a couple simple effects in a prototype app and trying to get code coverage branches percentage up, yet I can't figure out what needs to be done here, any suggestions?

![2017-06-21_0-32-54](https://user-images.githubusercontent.com/12227583/27339001-eb401bf6-5619-11e7-8e3f-c48181b3006f.png)

![2017-06-21_0-39-21](https://user-images.githubusercontent.com/12227583/27339077-23f696d2-561a-11e7-8249-7cfa0c39e46f.png)

**Comment by PhillipZada** [comment]
Same issue found here: https://github.com/angular/angular-cli/issues/5526

**Comment by brandonroberts** [comment]
This isn't an ngrx issue but an issue with the coverage collector.
