### ISSUE TITLE
Actions lift property should match the RxJs profile

### ISSUE THREAD

**Issue by kilian-ito** [ngrx/effects#161]
The interface of RxJs `Observable<T>` defines lift function as
```typescript
lift<R>(operator: Operator<T, R>): Observable<R>`
```

The override of lift in Action class should be
```typescript
lift<Action>(operator: Operator<any, Action>): Observable<Action>;
```
instead of
```typescript
lift(operator: Operator<any, Action>): Observable<Action>;
```

The error is reported by TypeScript > 2.4.1:

```
The 'this' context of type 'Actions' is not assignable to method's 'this' of type 'Observable<any>'.
   Types of property 'lift' are incompatible.
     Type '(operator: Operator<any, Action>) => Observable<Action>' is not assignable to type '<R>(operator: Operator<any, R>) => Observable<R>'.
       Types of parameters 'operator' and 'operator' are incompatible.
         Type 'Operator<any, R>' is not assignable to type 'Operator<any, Action>'.
           Type 'R' is not assignable to type 'Action'.
```

**Comment by tavelli** [comment]
do u know what version of typescript introduced this? looking to roll back to earlier version until this fix goes in

**Comment by gregbown** [comment]
@tavelli I only get the error when trying to upgrade from TypeScript 2.4.0 to 2.4.1
Tested it twice now.

**Comment by ryzy** [comment]
I've upgraded from 2.3.1 to 2.4.1 and have the same issue.

**Comment by brandonroberts** [comment]
This is a known TypeScript issue: See https://github.com/angular/angular/issues/17800#issuecomment-311775922

**Comment by fletchsod-developer** [comment]
Actually, it is not a `TypeScript` issue.  Just a `rxjs` issue that been there for a while and was never caught, until `TypeScript` start having stricter checking that found the `rxjs` error.

**Comment by gregbown** [comment]
Confirmed effects issue/error described is resolved.  Thank you @brandonroberts
Angular 4.2.6, TypeScript 2.4.1, rxjs 5.4.2, ngrx/store 2.2.3, ngrx/effects 2.0.4

**Comment by viktorstaikov** [comment]
Is there a workaround or something for now?

**Comment by pablopereira27** [comment]
This is enough... "@ngrx/effects": "^2.0.4", "@ngrx/store": "^2.2.3",
