### ISSUE TITLE
runAfterBootstrap in 4.X?

### ISSUE THREAD

**Issue by pjmagee** [ngrx/effects#170]
I am currently using a package called @ngx-config to bootstrap my application configuration via HTTP. I have some @Effects classes where I inject some services that use configuration that is bootstrapped and to get this configuration to work, I had to run these Effects with `EffectsModule.runAfterBootstrap` however now, with the upgrade to 4.X this no longer exists and now my configuration is not being bootstrapped prior to the effects being injected with services.

Any suggestions?

I'm literally stuck because of this change and I've looked everywhere.

**Comment by PrivateMeggido** [comment]
Same issue here. Trying to find a workaround that allows me to run 4.x but for now stuck in 2.x until I figure this out.

**Comment by brandonroberts** [comment]
@PrivateMeggido see https://github.com/ngrx/platform/issues/174#issuecomment-326468619
