### ISSUE TITLE
Single action dispatch results in multiple effect call until Maximum call stack size exceded

### ISSUE THREAD

**Issue by alexandr-sizemov** [ngrx/effects#178]
@Effect()
  public loadAccommodations$: Observable<Action> = this.actions$
    .ofType(PAA.PROPERTY_LOAD_REQUEST)
    // .debounce(300) introducing this mitigates the flood but does not resolve the issue
    .switchMap((action: Action) => {
      // loading logic called multiple times
      return this.propertyService.load(action.payload);
    });

After dispatch PAA.PROPERTY_LOAD_REQUEST only **once** my effect intercepts this action many times until **Maximum call stack size exceeded.**

Versions:
"angular/core": "2.4.6",
"@ngrx/core": "^1.2.0",
"@ngrx/store": "^2.2.1",
"@ngrx/effects": "^2.0.1",
"rxjs": "5.0.2",

Note: effects are registered only once in app.module.

**Comment by ndaroeya** [comment]
I got same problem.

```
@Effect()
login$: Observable<Actions> = this.action$
  .ofType(auth.AUTH_LOGIN)
  .map(toPayload)
  .switchMap(loginData => {
    if(loginData.credential.username == '' || loginData.credential.password == '') {
    	return empty();
    }

    let mappedActions;

    return this.authentication.login(loginData.credential)
      .map(jwt => {
      	if(jwt.message)
      		return new auth.AuthLoginFailAction(jwt.message)
      	else {
          mappedActions = [new auth.AuthLoginSuccessAction(jwt), new auth.AuthRedirectHomeAction(loginData.redirectRoute)];
        }
      })
      .mergeMap(val => mappedActions)
      .catch((error) => {
        return of(new auth.AuthLoginFailAction('Login failed.'));
      })
  });

//PROBLEM IS HERE
@Effect()
loginSuccess$: Observable<Action> = this.action$
  .ofType(auth.AUTH_REDIRECT_HOME)
  .do(data => {
    return this.router.navigate([data.payload]);
  });
```
Version:

1. "angular/core": "^4.0.0",
2. "@ngrx/core": "^1.2.0",
3. "@ngrx/effects": "^2.0.4",
4. "@ngrx/store": "^2.2.3",
5. "rxjs": "^5.1.0",

The problem is that AUTH_REDIRECT_HOME action dispatched multiple times causing the Effect executed multiple times too. What should I do with this problem?

Thank you.

**Comment by alexandr-sizemov** [comment]
Hi @ndaroeya your problem is different from mine.
In your case the issue is unrelated with effects because the effect itself is working as expected: _every time AUTH_REDIRECT_HOME is dispatched the listening effect is executed_.
Probably you have an actions loop, could it be AUTH_REDIRECT_HOME action triggers AUTH_LOGIN action in some way?

**Comment by alexandr-sizemov** [comment]
In my case the problem was caused by takeUntil in this piece of code:

```
 return this.propertyAccommodationsService.loadAccommodations(action.payload.id)
.takeUntil(this.loadAccommodations$) 
```

By dispatching 2 PROPERTY_LOAD_REQUEST actions, the second one triggered takeUntil() operator which resulted in multiple effects calls.

**Comment by brandonroberts** [comment]
@ndaroeya you need to add `dispatch: false` inside your `Effect` decorator since you aren't returning a new action, otherwise you'll just end up in a loop of the same action.
