### ISSUE TITLE
OpaqueToken deprecated in Angular 5.0.0

### ISSUE THREAD

**Issue by antangeles** [ngrx/effects#184]
Since upgrading to  Angular 5.0.0 ngrx effects and store throw errors "export 'OpaqueToken' was not found in '@angular/core'.

Per Angular's changelog:
https://github.com/angular/angular/blob/master/CHANGELOG.md
OpaqueToken has been removed as it was deprecated since v4. Use InjectionToken instead.

**Comment by MikaAK** [comment]
Upgrade this is not an issue in current build

**Comment by BoCsA** [comment]
The same problem here.

**Comment by brandonroberts** [comment]
V2 will not be updated to support Angular 5. See https://github.com/ngrx/platform/issues/538#issuecomment-342648123
