### ISSUE TITLE
Issue setting up runEffects with no @Effect still in place

### ISSUE THREAD

**Issue by iskandersierra** [ngrx/effects#24]
When I started an empty angular-cli project, I added a TestEffects class for testing this library, and I encountered an ObjectUnsubscribedError. This was a somewhat difficult to catch error. Finally I found that the Store<AppState> was being disposed because the effect observable was completing it, so any posterior subscription to the Store gave me this error.

I believe the effects stream should never end (compete or error). Maybe it should send a couple of special actions for those cases, but never finish the store. Event when you know there will be no more effects, the application is not done yet.

I might be wrong in the causes of this problem, but if I'm not, when all effects in the app are completed or errored, the store gets terminated and that is not a behavior I would want by default.

**Comment by MikeRyan52** [comment]
Should be fixed in v2.0.0.
