### ISSUE TITLE
[Question] Where is the code that calls the action at the end of an effect ...

### ISSUE THREAD

**Issue by emcpadden** [ngrx/effects#31]
Hi guys, 
First of all, let me compliment you on this amazing library.  I am pretty new to Functional Reactive programming and using ngrx has been a real boot camp for me.  I am trying to wrap my head around this stuff and it really makes my head spin ... in a good way ;) 

I just started using @Effects to call my backend services, and at the end of the effect I map to the success action (see my code below):

` @Effect() loadVendorExpenseTrendData$ = this.updates$
        .whenAction(VendorExpenseTrendDataActions.LOAD_VENDOR_EXPENSE_TREND_ITEMS)
        .map(payload => {
          console.log('Effect: VendorExpenseTrendDataActions.LOAD_VENDOR_EXPENSE_TREND_ITEMS called');
          return payload;
        })
        .switchMap(payload => (this.expensesService.loadVendorExpenseDashboardData())
          .map(vendorExpenseData => {
            console.log('Effect: About to call VendorExpenseTrendDataActions.LOAD_VENDOR_EXPENSE_TREND_ITEMS_SUCCESS');
            return this.vendorExpenseTrendDataActions.loadSuccess(vendorExpenseData);
          })
        );
`

I've been trying understand how the Effects work.  I think I get how they are called using the whenAction which in the code looks like it is implemented using an rxjs filter.

What I am struggling with is how the Effect knows to dispatch the action I return.  I am looking at the code and I am just having a hard time understanding how this is happening.  I was hoping that maybe you could help me understand this a little or point me to where I should be looking in the code.  I really want to understand this so it doesn't seem like magic to me.

Thanks again for all your hard work on ngrx!!!  I really want to better understand it and hopefully one day become an expert because I think it will open my mind up to the world of FRP.

...Ed

**Comment by MikeRyan52** [comment]
The `Store` in ngrx/store is both an `Observable` of state and an `Observer` of actions: https://github.com/ngrx/store/blob/master/src/store.ts#L12

An observer is really just a simple object with `next(val)`, `error(e)`, and `complete()` methods and can be passed to any subscription to _observe_ and observable:

```ts
Observable.interval(1000).subscribe({
  next(val) {

  },
  error(e) {

  },
  complete() {

  }
})
```

Because `Store` is an observer of actions, ngrx/effects subscribes your effects and passes `Store` as the observer: https://github.com/ngrx/effects/blob/master/lib/effects.ts#L22

Hope that helps!

**Comment by emcpadden** [comment]
Ahhh ... since I'm so new to FRP and functional programming in general, I'm still bending my mind to understand it but the light bulb did go off, no matter how dim :)

I get it that the store subscribes to the affect and I now see how the action gets dispatched.  THANKS!!!
