### ISSUE TITLE
Using angular-builds, getting: Generic type 'Type<T>' requires 1 type argument(s). -> node_modules/@ngrx/effects/module.d.ts

### ISSUE THREAD

**Issue by qdouble** [ngrx/effects#36]
I think this is due to this commit: https://github.com/angular/angular/commit/b96869afd2bdd3ad8c5b7477da647af628e383aa
So `Type` needs to be updated to `Type<any>`

**Comment by j2L4e** [comment]
#39

**Comment by MikeRyan52** [comment]
Fixed in v2.0.0
