### ISSUE TITLE
Effect won't run again after bad response from server.

### ISSUE THREAD

**Issue by theWaR13** [ngrx/effects#38]
I've created a simple login form. When user press login button i make a dispatch to the store
```
this.store.dispatch(this.loginActions.tryLogin(loginData));
```

This action goes to effect which is:

```
  @Effect() tryLogin$ = this.actions$
    .ofType(LoginActions.TRY_LOGIN)
    .map(action => action.payload.data)
    .switchMap(payload => this.apiService$.handleLogin(payload))
      .map(res => this.loginActions.loginSuccessful(res.data.authentication_token))
      .catch(() => Observable.of(this.loginActions.loginFailed()));
```

And my ApiService is:

```
  handleLogin(authData: ILoginForm): Observable<any> {

    console.log(authData);

    const body = JSON.stringify(authData);
    const headers = new Headers({
      'Content-Type': 'application/json;charset=utf-8'
    });
    const options = new RequestOptions({headers: headers});

    return this.http.post('/api/v1/sessions/', body, options)
                    .map((res: Response) => res.json());
                    .catch(this.handleError);

  }

  private handleError(err: any) {
    console.log('Error! ', err);

    return Observable.throw(err);
  }
```

So if user enter a correct pair (login/password) it's ok and everything works fine. He may press login button 5 times and the request will go to the server 5 times. But if pair is incorrect, only one request goes to the server and then nothing happens. If user will press login button again, it will make dispatch, but there will not a request, which should be called by the effect. I guess that effect stops working because of wrong handling of mistakes (catch block). Any ideas what can it really be? I can provide more code if needed. Thanks in advance.

UPD. 
I've added a simple button with test action. So if i enter a correct pair and then press this button, instead of test action it calls TRY_LOGIN action.

**Comment by theWaR13** [comment]
Wrong parenthesis in switchMap, sorry.

**Comment by nigeman** [comment]
@theWaR13 can you explain this further ? :) I am literally running into this issue and cant understand what you mean.

Cheers

**Comment by theWaR13** [comment]
@nigeman well. In this string just remove the last parenthesis and put it in the end. Should work :)

```.switchMap(payload => this.apiService$.handleLogin(payload))```

**Comment by nigeman** [comment]
Got it and it makes sense- the catch should happen in the switchmap

**Comment by 10freefingers** [comment]
I had the same problem. I wonder if there's an option to do it like you planned in the beginning - to use a more generic catch, after a switch map and at the end of an effect?

**Comment by jcroll** [comment]
To quickly help anyone trying to consume this, the effect should be rewritten as:
```javascript
    @Effect() tryLogin$ = this.actions$
    .ofType(LoginActions.TRY_LOGIN)
    .map(action => action.payload.data)
    .switchMap(payload => {
      return this.apiService$.handleLogin(payload)
        .map(res => this.loginActions.loginSuccessful(res.data.authentication_token))
        .catch(() => Observable.of(this.loginActions.loginFailed()));
      }
    );
```

Thanks @theWaR13
