### ISSUE TITLE
error getting after update to beta3

### ISSUE THREAD

**Issue by smkamranqadri** [ngrx/effects#41]
getting below error after update to beta 3...

ERROR in /Volumes/data/onseen-admin-client/node_modules/@ngrx/effects/module.d.ts
(3,22): error TS2315: Type 'Type' is not generic.

**Comment by fxck** [comment]
that is the error beta 3 is supposed to fix, clear your npm cache and node_modules

**Comment by smkamranqadri** [comment]
done and result is same!

**Comment by adamfinstorp** [comment]
Same for me unfortunately

**Comment by MikeRyan52** [comment]
Beta 3 is for Angular 2 RC 6, Beta 2 is for Angular 2 RC 5. The only change between beta 2 and beta 3 is the generically typed `Type` type.

**Comment by milkisevil** [comment]
Incorrect `peerDependency` then [on beta 3](https://github.com/ngrx/effects/blob/v2.0.0-beta.3/package.json#L37) (it has rc.5)
