### ISSUE TITLE
No exported member 'StateUpdates'

### ISSUE THREAD

**Issue by adamfinstorp** [ngrx/effects#42]
Am I doing something wrong here? Running v2.0.0-beta.2

`import { Effect, StateUpdates } from '@ngrx/effects';`

results in:

_error TS2305: Module '"my-path/node_modules/@ngrx/effects/index"' has no exported member 'StateUpdates'._

**Comment by fxck** [comment]
There is no `StateUpdates` anymore, when you are using one of the betas, that is.

See https://github.com/ngrx/effects/pull/35
