### ISSUE TITLE
Don't have toPayload or StateUpdates as exported members?

### ISSUE THREAD

**Issue by 281330** [ngrx/effects#44]
I am using "@ngrx/effects": "2.0.0-beta.2", and I tried the latest version too, but I am not able to import State Updates or toPayload because it says they are not exported members.

So, I'm only able to use Effect and Actions :(

Am I doing something wrong?

**Comment by awerlang** [comment]
See #35 and #32 (for context)

**Comment by smith64fx** [comment]
Where has the payload gone?

**Comment by abdulhaq-e** [comment]
@smith64fx According to @MikeRyan52 `toPayload` was simply forgotten. It will be added later.

For the time being, see Effects V1 for `toPayload` implementation, it's pretty simple.

**Comment by MikeRyan52** [comment]
`toPayload` is back in v2.0.0. `StateUpdates` has been removed in favor of `Actions`.
