### ISSUE TITLE
When bootstrapping not in root module effects are applied multiple times

### ISSUE THREAD

**Issue by olaf89** [ngrx/effects#45]
I had effects bootstrapped in lazy loaded module, when browsing between child pages, each time effects were called one more time. 

LazyLoadedModule  => EffectsModule.run(SomeEffects)

LazyLoadedModule  routing: 
 children: [
            { path: '', redirectTo: 'xxx', pathMatch: 'full'},
            {
                path: 'xxx',
                component: Cmp1,
            },
            {
                path: 'yyy',
                component: Cmp2
            }
In this example every time navigation happens from Cmp1 to Cmp2, effects were called one more time

VERSION:     "@ngrx/effects": "2.0.0-beta.2",

**Comment by brandonroberts** [comment]
If you are on RC5, there exists a bug where lazy loaded modules are recreated every time you navigate to them by the router. This bug no longer exists in RC6.

**Comment by jimitndiaye** [comment]
@brandonroberts are you supposed to use EffectsModule.run(effect) or EffectsModule.runAfterBootstrap(effect) for lazy loaded modules?

**Comment by brandonroberts** [comment]
@jimitndiaye you use `EffectsModule.run(effect)`. You only use `EffectsModule.runAfterBootstrap(effect)` in your root module.

**Comment by brandonroberts** [comment]
Is this still an issue?

**Comment by bradseefeld** [comment]
I believe so. I am seeing a similar behavior. I have a number of modules that I import into my root module. I am seeing effects fired twice regardless of whether I call `EffectsModule.run(MyEffect)` in the root module, or one of the others.

This is with angular 2.0.0 and ngrx/effects 2.0.0-beta.3.

**Comment by brandonroberts** [comment]
Can you reproduce the bug in a plunker? http://plnkr.co/edit/BWMndF?p=preview

**Comment by Matmo10** [comment]
@brandonroberts Can you clarify this a little bit?

According to what you said above: In your main module , you should be using `.runAfterBootstrap()` for every effect in your main module, and then `.run()` for every effect in your lazy loaded modules? And what about synchronous modules?


I'm using your `angular2-router-loader`, if that matters. 

Also, I'm seeing 3 `@ngrx/store/init` actions pass through my store on startup and duplicates of all my events when the StoreDevTools / <ngrx-store-log-monitor> is enabled.   If I disabled the storedevtools then my duplicate actions go away , but I still see 2 `@ngrx/store/init` actions (shouldn't there only be 1?).

**Comment by MikeRyan52** [comment]
@Matmo10 Sounds like you've imported `StoreModule` multiple times?

**Comment by bradseefeld** [comment]
Plunkr here: http://plnkr.co/edit/d6Q4KDR8UpT0F9rpROJ3 Its a bit messy but I tried to keep it concise by putting everything in a single file.

Please look at the `brad.module.ts` file. This includes a `BradModule`, which imports the `BradEffects`.

In `Home` I wired up the login button to also dispatch the 'SEE_ME_TWICE' action type. The effect listening for this action (defined in `brad.module.ts`) will console.log every time it sees that action. 

Note that clicking 'login' will double logs from the effect. I am logging in the effects constructor, and this only logs once, so I am quite certain there is only one BradEffects instantiated.

**Comment by bradseefeld** [comment]
@brandonroberts, @MikeRyan52, any thoughts on this? I know you guys are busy, but was hoping to get confirmation that it is indeed a bug, and not misconfiguration/misuse of the library on my part.

**Comment by brandonroberts** [comment]
@bradseefeld I saw your plunker. Why are you using `EffectsModule.run(BradEffects)` and using the `mergeEffects` inside the `BradEffects` class? You only need the first one since the effects are subscribed automatically with the `.run` method.

**Comment by bradseefeld** [comment]
Thanks @brandonroberts! That was indeed the issue. As to why I was doing it, I cannot say... I thought thats what I saw in the example app, but I just looked at it again and you guys arent calling `mergeEffects` there. May have seen it on someones blog or an older example.

Thanks for your help! We're loving ngrx!

**Comment by cgatian** [comment]
I think this issue can be closed
