### ISSUE TITLE
update$ not give state anymore?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/effects#47]
I am using thew latest version, I can see that the update change to action object only and remove the state from update$, but I need to fetch things from the store to build my payload. 
how should I do it now? get from the store from the container (who do dispatch) or any other way within the effect?

thank!

**Comment by fxck** [comment]
see https://github.com/ngrx/effects/pull/35 and https://github.com/ngrx/effects/pull/32 it was removed, you can get state to your action by doing this

```typescript
actions$
  .ofType('login')
  .withLatestFrom(store$)
  .map(([ action, state ]) => ({ action, state }))
```

**Comment by wizardnet972** [comment]
Great! So Fast! Thanks @fxck ! :)

**Comment by michaeljpeake** [comment]
As this is breaking change to @ngrx/effects, it would be great if this was shown in the README.md. I just updated and had no idea why I had to completely rewrite all my effects.

**Comment by wizardnet972** [comment]
@michaeljpeake see this:
https://github.com/wizardnet972/tic-tac-toe/blob/master/src/client/app/tic-tac-toe/effects/board.effects.ts#L16

(example app with angular2 final and based on ngrx best practices, https://github.com/ngrx/example-app)
