### ISSUE TITLE
v2: Side effect conditional on state value?

### ISSUE THREAD

**Issue by davidmarquis** [ngrx/effects#49]
With v1, I was able to have a side-effect run conditionally based on current state value (notice the `filter()` call):

``` js
@Effect() refreshResultsWhenInBrowseMode$ = this.updates$
    .whenAction(SearchActions.CHANGE_MODE, SearchActions.CLEAR_SEARCH)
    .filter(stateUpdate => stateUpdate.state.search.mode === SearchMode.BROWSE)
    .map(stateUpdate => stateUpdate.state.search.query)
    .map(query => this.searchActions.search(query));
```

This is because in v1 an instance of `StateUpdate` was emitted by the `StateUpdates` observable. The `StateUpdate` interface had both `action` and `state` available.

With v2, instances of `Actions` are now emitted, which removes the access to the state. 

Any idea on what would be the best option to run a side effect depending on a value in the current state with v2?

**Comment by awerlang** [comment]
To keep the v1 approach: https://github.com/ngrx/effects/pull/32#issuecomment-239162605
or you could dispatch a new action and handle the condition on the reducer. But I'd kept the previous way.

**Comment by davidmarquis** [comment]
Thanks @awerlang it works!

For posterity, here's what I changed the above code to:

``` js
@Effect() refreshResultsWhenInBrowseMode$ = this.actions$
    .ofType(SearchActions.CHANGE_MODE, SearchActions.CLEAR_SEARCH)
    .withLatestFrom(this.state$)
    .filter(([action, state]) => state.search.mode === SearchMode.BROWSE)
    .map(([action, state]) => state.search.query)
    .map(query => this.searchActions.search(query));
```

I also had to inject the `Store` instance as `state$` in the class constructor:

``` js
constructor(private actions$: Actions,
              private state$: Store<AppState> 
...
```

**Comment by JonnyBGod** [comment]
I am getting ```Property 'withLatestFrom' does not exist on type 'Actions'.```

**Comment by davidmarquis** [comment]
The `Actions` class is an `Observable<Action>`, `withLatestFrom` comes from `Observable`, which is from the `rxjs` library. What version of `rxjs` are you using?

Hint: 

    npm ls | grep rxjs

**Comment by JonnyBGod** [comment]
rxjs@5.0.0-beta.12

**Comment by MikeRyan52** [comment]
You have to import operators:

```ts
import 'rxjs/add/operator/withLatestFrom';
```

**Comment by JonnyBGod** [comment]
Well I have tried that a few days ago with no luck but now it is working. Thanks

**Comment by Sn3b** [comment]
Hi,

I know this is quite old already but I've just come across it as I needed this exact solution, seems to work just fine, but I fail to understand something, if anyone could explain I'd be greatful :)

And in advance I apologise as my question might seem stupid and totally off topic.

I fail to understand why we need the square brakets in the line:
`.map(([action, state]) => state.search.query)`

Obviously I tried without and it's no good ;)

Thanks!

**Comment by bertofer** [comment]
@Sn3b It's because of the operator `withLatestFrom` of Observables, that emits an Array as value, with position 0 the source observable, and position 1 the observable inside the `withLatestFrom` operator. 

It can be expressed as [action, state] thanks to the [destructuring assignment](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) of ES6 ;)

Hope it clarifies your question!

**Comment by Sn3b** [comment]
I knew it was because of `withLatestFrom`, had a look at the signature that shows it returns a  `Observable<[T, T2]>`, but I could not understand how this was even possible...

Thank you for this clarificaion, it helps alot! :)

**Comment by pos1tron** [comment]
Hello. I'm new to ngrx to please excuse my ignorance. I'm trying to use this in my code, but when it's included, none of my dispatches app wipe will enter the action$ queue... Can anyone help me understand what i'm doing wrong? Here's the code:
```js
@Injectable()
export class EcosystemEffects extends BaseEffect {

  @Effect() getUserAccountPDomainIfNotExist$ = this.actions$
    .ofType(EcosystemActionTypes.GET_USER_ACCOUNT_PDOMAIN_IF_NOT_EXISTS)
    .withLatestFrom(this.selectedPrimaryDomain$)
    .filter(([action, state]) => state === null)
    .map(() => Observable.of({type: EcosystemActionTypes.GET_USER_ACCOUNT_PDOMAIN}));

  private selectedPrimaryDomain$: Observable<IPrimaryDomain>;

  constructor(
    private store: Store<IAppState>,
    private actions$: Actions,
    private ecosystemService: DjEcosystemService
  ) {
    super()
    this.selectedPrimaryDomain$ = this.store.select(getSelectedPDomain);
  }

}
```
I'm not even dispatching an action of type `EcosystemActionTypes.GET_USER_ACCOUNT_PDOMAIN_IF_NOT_EXISTS`. When I comment out `getUserAccountPDomainIfNotExist$` everything works fine.

**Comment by Sn3b** [comment]
Yes that's what I was going to say, use the store directly in your call to withLatestFrom. However, do you even need that since you're returning an action without payload?

**Comment by pos1tron** [comment]
@Sn3b All i'm trying to do is conditionally fire an action if some data doesn't exist. So I don't actually need the data i'm getting in there for the return action. Just need to know if it's there or not.

**Comment by Sn3b** [comment]
And what if it does exist?
What about something like:

```javascript
  @Effect() getUserAccountPDomainIfNotExist$: Observable<Action> = this.actions$
    .ofType(EcosystemActionTypes.GET_USER_ACCOUNT_PDOMAIN_IF_NOT_EXISTS)
    .withLatestFrom(this.store)
    .map(([action, state]) => state.ecosystem.selectedPDomain)
    .switchMap(selectedPDomain => {
      if (selectedPDomain == null)
        return  Observable.of({type: EcosystemActionTypes.GET_USER_ACCOUNT_PDOMAIN});
      else
        // ???
    });
```

**Comment by pos1tron** [comment]
I was assuming that because I have a filter on there, that the switchmap would only fire it doesn't exist, thus in that block, I would never need to handle when it does exist.

**Comment by codenode711** [comment]
Hello. I'm new to ngrx so please excuse my ignorance. I am trying to use the following code to check the state of the property. 

`
    @Effect()
    save$ = this.action$
    .ofType(ItemDetailsActions.UPLOAD)
    .withLatestFrom(this.state$)
    .filter(([action,state])=>state.itemdetails.changed === true)
    .map((t)=>console.log('I am called'))   
    .catch(error => of(new ItemDetailsActions.LoadFailure(error)))`

I call the Upload Action with no payload. I want to push data (itemdetails) to the server only if the changed flag is true. 
The itemdetails has the following properties 

`  loading: boolean;
    loaded: boolean;
    changed:boolean;
    itemdetails: ItemDetails[] | null;`.

I get the Failure with 

`LoadFailure {payload: TypeError: Cannot read property 'changed' of undefined
    at http://localhost:4200/1.chunk.js:2225:…, type: "[ItemDetails] Load Failure"}`

Can anyone help me with what am I doing wrong ?

**Comment by krjordan** [comment]
@codenode711 At a glance, it looks like your `changed` property is not being set in your initial state to `false`. You might do better troubleshooting your error on the [ngrx Gitter channel](https://gitter.im/ngrx/platform).

**Comment by Sn3b** [comment]
Looks like your `state.itemdetails` (where you filter) is undefined
