### ISSUE TITLE
v2: Dependency injection issue?

### ISSUE THREAD

**Issue by darren-temenos** [ngrx/effects#50]
There appears to be an issue with dependency injection when using EffectsModule.run in lazy loaded modules where a dependent service is exported through a barrel. For example:

_some.module.ts_
```
import {SomeEffects} from 'some.effects.ts';
@NgModule({
  imports: [
    EffectsModule.run(SomeEffects)
  ],
  providers: [
    SomeService
  ]
})
```

_some.effects.ts_
```
import {SomeService} from './';
@Injectable()
export class SomeEffects {
  constructor(private service: SomeService) {}
}
```

_index.ts_
```
export * from some.service.ts
```

_some.service.ts_
```
@Injectable()
export class SomeService {
  constructor() {}
}
```

Throws the following exception at runtime in the browser:
```
Can't resolve all parameters for SomeEffects: (?)
```

This does not happen when using EffectsModule.run in the root _app.module.ts_.

**Comment by MikeRyan52** [comment]
Can you put a reproduction together for this?

**Comment by darren-temenos** [comment]
Closing. Related to https://github.com/webpack/webpack/issues/1788.
