### ISSUE TITLE
Does your example should be considered to best practice?

### ISSUE THREAD

**Issue by stavalfi** [ngrx/effects#52]
I'm new to ngrx and trying to learn when it is appropriate to use ngrx/effects and how.

I'm facing design problems with how to develope all related thing to logging in and logging out to my application.

After reviewing your exmple, I found some design problems.
[I have wrote a well detailed question in stack-code review.](http://codereview.stackexchange.com/questions/141969/designing-redux-state-tree
)
Please look and respond here or there.

Thanks!

**Comment by MikeRyan52** [comment]
Closing this since since there are no issues.

Thanks for the interesting discussion you've spurred on stack-code! I'll take a look and might add feedback if I can find time :)

**Comment by stavalfi** [comment]
Hi @MikeRyan52 and thanks for the feedback! I will love to hear your opinion and how to make my design better.
Thanks!
