### ISSUE TITLE
'package.json' to reference 'bundles/effects-testing.umd.js'

### ISSUE THREAD

**Issue by cartant** [ngrx/effects#53]
Thanks for the new release.

It's apparent that the Angular 2 approach of using `main` and `module` entry points in the `package.json` has been adopted. However, there is an issue with deep-path imports like this:

```
import { EffectsRunner, EffectsTestingModule } from "@ngrx/effects/testing";
```

If Browserify is used, the above import brings in the ES modules  and the bundling fails with an error.

With the Angular 2 modules, an additional `package.json` file is included in the distribution's `testing` directory which redirects to the UMD bundle, solving the problem. With the `@ngrx/effects` module, placing a `package.json` file with the following content into the `testing` directory solves the problem:

```
{"main": "../bundles/effects-testing.umd.js"}
```

**Comment by MikeRyan52** [comment]
Thanks, I'll get a fix in for this tomorrow.

**Comment by onlyann** [comment]
Awesome. I was experiencing this issue and it's good to understand what was going on.
Is there any resource that explains how tools like Webpack `package.json` definition to resolve module dependencies? It's not clear to me what tells Webpack that it needs to load the umd bundles.

**Comment by cartant** [comment]
@onlyann Browserify mimics Node's `node_modules` behaviour. Presumably, Webpack does the same. The behaviour is outlined [here](https://nodejs.org/api/modules.html#modules_all_together).

The how-to-use-ES-modules thing for `package.json` files is pretty much bleeding edge. If you're interested, the `main`/`module` mechanism  that has been adopted by Angular 2 is mentioned in [this issue](https://github.com/ReactiveX/rxjs/issues/1671#issuecomment-245433514). And it seems to correspond to the "*In Defense of .js*" option that's mentioned in [this blog post](https://nodesource.com/blog/es-modules-and-node-js-hard-choices/).

**Comment by philipooo** [comment]
This hits me today. Using Webpack my test result in `SyntaxError: Use of reserved word 'export'`. The workaround provided by @cartant works for me, but not for our buildserver as it downloads a fresh copy of the ngrx npm package.

**Comment by ttrabold** [comment]
I'm experiencing the same issue as @philipooo.

**Comment by turnbullm** [comment]
Until this is fixed and released, place this within your `package.json`:

```
"scripts": {
    "postinstall": "echo '{\"main\": \"../bundles/effects-testing.umd.js\"}' > ./node_modules/@ngrx/effects/testing/package.json"
}
```

Fix instantly with `npm run postinstall`, and then fix is automatically applied when needed moving forward

**Comment by danielsuter** [comment]
@MikeRyan52 Have you already had time to provide a fix?

**Comment by jalalat** [comment]
@turnbullm how i can undo this script. After your suggestion my test server even would not start. 

@MikeRyan52 any updates if it is fixed?

**Comment by vaclav-antosik** [comment]
Hello, we've started to use ngrx/effects in our project and we would like to write some tests for our effect classes. We do not prefer to use offered workaround. So we are waiting for proper fix here :-)

**Comment by PonomarovAndriy** [comment]
Hi guys,
we are also using ngrx/effects and for us it is important to have a proper fix to avoid the workaround.
Thank you

**Comment by shiptoncraig** [comment]
@mikerhyssmith and I had this issue when trying to write a test in Angular 2 using Webpack 1.  We got around it by adding the NormalModuleReplacementPlugin to our webpack test config:

```javascript
new NormalModuleReplacementPlugin(
/@ngrx\/effects\/testing/,
path.resolve(__dirname,'../node_modules/@ngrx/effects/bundles/effects-testing.umd.js')
```

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
