### ISSUE TITLE
Expand EffectsModule.run() to accept an array of Effects?

### ISSUE THREAD

**Issue by brian428** [ngrx/effects#57]
To avoid having to manually trigger EffectsModule.run() on every Effect, I've been exporting an array of Effects and doing this in my app module:
```
@NgModule({
  imports: [
    ...effects.map( effect => EffectsModule.run( effect ) )
  ]
```

This works fine in normal dev and prod mode, but using the AoT compiler, I get: `Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function` .

Apparently, AoT doesn't like the dynamically-executed `run()` logic. 

Would it be possible to expand the `run()` method to accept an array of Effects in addition to a single Effect?

**Comment by davidmarquis** [comment]
+1 I agree this would make sense... as a workaround, did you try `replacing the lambda with a reference to an exported function`?

**Comment by MikeRyan52** [comment]
We have an idea on how to make a dynamic API that _might_ look like this:

```ts
EffectsModule.runDynamically([
  EffectA,
  EffectB,
  EffectC,
  ...
]);
```

The problem is that the DI for the effect classes won't be able to be statically analyzed, meaning you won't be able to tree shake `ReflectiveInjector` and you will always have to ship your app with the reflect-metadata shim.

**Comment by BrainCrumbz** [comment]
@davidmarquis just thinking out loud: doesn't `EffectsModule.run` already represent a reference to an exported function? So that one could just go with:

```
  imports: [
    ...effects.map(EffectsModule.run)
  ]
```

?

**Comment by davidmarquis** [comment]
@BrainCrumbz one form probably can be statically analyzed (being a direct reference to the target function), while the other form - the one from the OP - I'm not sure...

**Comment by BrainCrumbz** [comment]
Actually my suggestion does not seem to work: trying right now and it complains about:

> Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ...

Also tried wrapping `EffectsModule.run` in a local function, with no luck.

**Comment by MikeRyan52** [comment]
Yup, writing a helper that reduces the number of times you have to call `EffectsModule.run()` while also being AOT compiler friendly is tricky.

As the AOT compiler matures and understands more code paths we'll revisit this issue. Thanks!

**Comment by BrainCrumbz** [comment]
For time being, we moved from this previous implementation:

```ts
const appEffects = [
  featureEffect1,
  featureEffect2,
  featureEffect3
];

// ...
  imports: [
    ...appEffects.map(EffectsModule.run)  // <-- does not work in AOT
  ]
```

to this one:

```ts
const appEffectsRun = [
  EffectsModule.run(featureEffect1),
  EffectsModule.run(featureEffect2),
  EffectsModule.run(featureEffect3)
];

// ...
  imports: [
    ...appEffectsRun
  ]
```

Given that at some point we **are** listing all single effects, we can as well invoke `EffectsModule.run` on each of them manually, not a huge deal.
