### ISSUE TITLE
Effect called multiple times if you subscribe to it

### ISSUE THREAD

**Issue by Bretto** [ngrx/effects#59]
I have  an Effect: 
```
@Effect()
  addTagToVideoEffect_ = this.appState_
    .ofType(TagActions.ADD_TAG_TO_VIDEO)
    .do(_=>console.log('TagActions.ADD_TAG_TO_VIDEO'))
    .map<AddTagToVideo>(action => action.payload)
    .switchMap((addTag: AddTagToVideo) => this.dtsiVideosService.addTagToVideo(addTag)
      .map((addTag: AddTagToVideo) => TagReducers.addTagToVideoComplete(addTag))
      .catch((err) =>Observable.throw(err))
    );
```

and in my view I am dispatching the `TagActions.ADD_TAG_TO_VIDEO`  and subscribing to it:
```
this.subscription = this.tagActions.addTagToVideoEffect_.subscribe(
      this.onAddTagSuccess,
      this.onAddTagError
    );

this.tagActions.addTagToVideo({videoId: this.videoId, tag: tag});
```

the `.tagActions.addTagToVideoEffect_.subscribe` results in having my effect called twice, is this a bug ? How can we get the results of the effects in the view without having the effect called twice ?

**Comment by fxck** [comment]
You should never subscribe to annotated effect, subscribe to the store instead.

**Comment by Bretto** [comment]
I posted on [stackoverflow ](http://stackoverflow.com/questions/39885705/angular-2-ngrx-store-and-effects-and-ephemeral-states). Could you show me how to subscribe to the store as I don't see how it could resolve the problem.

**Comment by fxck** [comment]
How to subscribe to the store? Inject it and do `.subscribe()` on it? You should never subscribe to an effect, not in the new(2.0.0) version anyway. I think you are misunderstanding how to use this lib, it's not a promise, it doesn't have any callbacks you can subscribe to. Pardon me if I'm wrong.

In the centerpiece of everything is the `@ngrx/store`, there are actions dispatched to the store, you can either "catch" these action in a reducer, or an effect(or both). When you catch an action in an effect(using `ofType()`), you can for example `switchMap`, this action to an async call, and then map the result to a different action, think `REQUEST_SOMETHING_ACTION` -> effect -> `SUCCESS_SOMETHING_ACTION`, this success action, which includes payload of your async call, will then be handled by a `something` reducer, filling it with data.

Then in your component, you can subscribe to this slice of state, by doing somethign along these lines

```
somethings$ = this._store.map(wholeStore => wholeStore.something)
```

you can then either subscribe to `somethings$` in your component's class, or you can directly use it in the template with the `async` pipe

```
<pre>{{ somethings$ | async | json }}</pre>
```

**Comment by Bretto** [comment]
Yes I know the ordinary flow, did you look at the [stackoverflow](http://stackoverflow.com/questions/39885705/angular-2-ngrx-store-and-effects-and-ephemeral-states) link above where I try to illustrate my current frustration with adding to the store the ephemeral states of a component form. Like: Action: __Pending__ then __Success__ or __Error__ and then after a second or two you have to reset the component form to __Pristine__ in the store, otherwise you would re-open this component with a big green tick illustrating __Success__. I know that I can solve all this by adding it to the store these states but that's so much boilerplate __Actions__ __Effects__ __Reducers__ for what needs to be done... If the subscription to the Effect was not generating __a second call__ on my Service ([stackoverflow](http://stackoverflow.com/questions/39885705/angular-2-ngrx-store-and-effects-and-ephemeral-states)) the problem would be solved. I do understand that this would bring a tight coupling between the component form and the Effect but this coupling in my case seems appropriate. Is there way to get those  `this.onAddTagSuccess, this.onAddTagError` in my view to fire without introducing those ephemeral state in the store ? I think that I wouldn't be the only one  appreciating it. Thank you for your feedback.

**Comment by RyanMcDonald** [comment]
Can you post the view code that is calling the code that dispatches the action?

**Comment by Bretto** [comment]
```
static ADD_TAG_TO_VIDEO = '(Action)[Tag] ADD_TAG_TO_VIDEO';
  addTagToVideo(obj: AddTagToVideo): void {
    this.store.dispatch({
      type: TagActions.ADD_TAG_TO_VIDEO,
      payload: obj
    });
  }
```

**Comment by RyanMcDonald** [comment]
Not actually sure what happens when you subscribe to an effect. It might be similar to subscribing to a piece of state in the store: when you subscribe, it will immediately return the last emitted value. This is so your view can have immediate access to a value, rather than waiting for the next state change.

What you could try is a global event system, so your view can listen to specific events that you define. Then when your Effect finishes, it can fire the event. Here are two places that have examples of that:
- http://stackoverflow.com/questions/34700438/global-events-in-angular-2
- https://scotch.io/tutorials/angular-2-http-requests-with-observables#component-interaction-what-you-may-not-know

Alternatively, if you just need to prevent your `addTagSuccess` or `addTagError` functions from executing the first time, you might be able to just skip the first emitted value of your observable:
```javascript
this.subscription = this.tagActions.addTagToVideoEffect_
  .skip(1)
  .subscribe(
    this.onAddTagSuccess,
    this.onAddTagError
  );
```

**Comment by Bretto** [comment]
I have found a solution: [stackoverflow](http://stackoverflow.com/a/39970185/1021888)
