### ISSUE TITLE
Question: how to get data from store in an effect

### ISSUE THREAD

**Issue by nitimmerman** [ngrx/effects#60]
Hi all,

At the moment i'm working on a piece of software whereby several pieces of data are stored in the application state. Now I want to combine those pieces and post them to the server.
It seems to me that effects only have access to the payload via the toPayload function but before i could utilize that function, I need to get the data into my component. This doesn't look like a good architecture to me as all the data is living in the appstate.

Or am I missing something obvious here?

**Comment by awerlang** [comment]
Search for withLatestFrom in this repo issues.

**Comment by wizardnet972** [comment]
https://github.com/ngrx/effects/issues/47#issuecomment-246955732

**Comment by nitimmerman** [comment]
Great! Thank you, that helped a lot.
