### ISSUE TITLE
Effect called twice

### ISSUE THREAD

**Issue by iwoogy** [ngrx/effects#61]
Hello

I'm writing a simple login component using ngrx, and the effect that controls de the remote call got called twice when the Action is dispatched.

I didn't subscribed to the effect as another issue mentioned.

I'm using Angular 2 Final and ngrx/effects 2.0.0.

Thanks in advance for your help.

**Comment by Bretto** [comment]
I have the same behaviour when I am registering the effects in different modules.
ie:
```
Module A import EffectsModule.run(AEffects),
Module B import EffectsModule.run(BEffects), and Module A
```

Than I have my Effect played twice... To circumvent the issue I am only using the ```EffectsModule.run(...)``` in Module Main.

**Comment by iwoogy** [comment]
Thanks Bretto, you are right, I was declaring the effects in 2 modules the AppModule and the StoreModule that was imported into the AppModule.

Problem solved.
