### ISSUE TITLE
Returning new observable

### ISSUE THREAD

**Issue by denkomanceski** [ngrx/effects#62]
The question is why I cannot return the same observable that entered in the effect and I must switchMap or return Observable.of() in order to not get in infinite loop?

Example (works):
```
  @Effect() load$ = this.actions
      .ofType('LOAD_ARCHETYPE')
      .map(action => {
          console.log(action);
          return Observable.of(action)
      });
```

Example (infinite loop):
```
  @Effect() load$ = this.actions
      .ofType('LOAD_ARCHETYPE')
      .map(action => {
          console.log(action);
          return action;
      });
```

sometimes I just need to do something like change loading value or call a rest api and thats why I created the effect in first place but why do I have to return a new observable and not the one that came at the effect?

Also, with the effects its not clear how to do AFTER action.. the effect gets called before an action is invoked and than it enters in the reducers, but how to know when the reducer is done and chain something after that ?

**Comment by awerlang** [comment]
> sometimes I just need to do something like change loading value or call a rest api and thats why I created the effect in first place but why do I have to return a new observable and not the one that came at the effect?

You want to handle the action but do not issue a new action? Use `@Effect({dispatch: false})`

> Also, with the effects its not clear how to do AFTER action.. the effect gets called before an action is invoked and than it enters in the reducers, but how to know when the reducer is done and chain something after that ?

This is wrong. First the reducer function takes place, only then effects run.

**Comment by denkomanceski** [comment]
Ye that is my bad.. so what is the best practice when I want to make something before it hits the reducer.. for example make a rest call ? Should I do it normally like usual and in the callback dispatch an action ?
Thanks

**Comment by awerlang** [comment]
I'd create a separate action, one only handled in an effect, that would dispatch another action handled by reducers.

**Comment by denkomanceski** [comment]
Ye that seemed like the only option how to finish the whole process with just dispatching action from some component.. but than I have 2 actions just to fetch + save the fetched data to the store.. if for every rest call I create 2 actions (one just effect and the other to save) I am afraid the the code will be come messy.. but if its the best practice ye..
