### ISSUE TITLE
How to disable the automatic effects that run after dispaching actions that did not change the state?

### ISSUE THREAD

**Issue by stavalfi** [ngrx/effects#63]
**How to disable the automatic effects that run after dispaching actions that did not change the state?**

It maby not a bug but this is not the behavior I want in my app.(I couldnt find a situation that this is usefull and now it causes a chain of events that I want to prevent from happening).
Is there a way to turn it off? If not, how to I override it in the source code in node_module/ngrx/effects?

I hope that I made my self clear.

Thanks everyone!

**Comment by awerlang** [comment]
I'm not sure I understand. You want effects to run if and only if an action resulted in a new state when running reducers?

**Comment by stavalfi** [comment]
Hi @awerlang, yes!

**Comment by awerlang** [comment]
You'd need to go the other way around: start from the state source itself then take the latest action.

```ts
@Effect() myEffect = this.store
    .let(s => s) // could take a slice or all of it
    .distinctUntilChanged(s => ...)  // may want to ignore duplicates when taking a slice
    .withLatestFrom(this.actions) // take the last action
    .filter(([state, action]) => action.type === YOUR_ACTION) // proceed only for some actions
    .map(([state, action]) => ...)
    ...
```

**Comment by stavalfi** [comment]
Okay nice this can work. Thanks very much! very creative ;D

I do hope ngrx team will support this in later versions by defualt. 

Thanks agian!

**Comment by MikeRyan52** [comment]
Closing as this sounds resolved.

@stavalfi feel free to open another issue if need be!
