### ISSUE TITLE
Effects not registered when using AOT compilation

### ISSUE THREAD

**Issue by jorgenfb** [ngrx/effects#71]
I'm using angular-cli@1.0.0-beta.18 to build my application. When running `ng serve -prod` everythings works as expected. Adding AOT compilation (`ng serve -prod --aot`) makes effects not work anymore. Actions are still dispatched (I see them passing through my reducers).

Dependencies:
├── @angular/XYZ@2.1.1
├── @angular/platform-browser@2.1.1
├── @angular/platform-browser-dynamic@2.1.1
├── @angular/router@3.1.1
├── @ngrx/core@1.2.0
├── @ngrx/effects@2.0.0
├── @ngrx/store@2.2.1

Are there any obvious stuff that I am missing?

My ngrx setup is mostly copied from the ngrx/example-app:

effects/project.ts:

```
@Injectable()
export class ProjectEffects {
    constructor(private api: ApiService, private action$: Actions) { }

    @Effect()
    load$: Observable<Action> = this.action$
        .ofType(project.ActionTypes.LOAD)
        .switchMap(update => this.api.getProjects()
            .map(projects => new project.LoadProjectSuccessAction(projects))
        );
}
```

actions/project.ts:

```
export const ActionTypes = {
    LOAD: type('[Project] Load'),
    LOAD_SUCCESS: type('[Project] Load success')
};

export class LoadProjectAction implements Action {
    type = ActionTypes.LOAD;
}

export class LoadProjectSuccessAction implements Action {
    type = ActionTypes.LOAD_SUCCESS;

    constructor(public payload: Project[]) { }
}

export type Actions
    = LoadProjectAction
    | LoadProjectSuccessAction

```

app.module.ts:

```
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        HttpModule,
        MaterialModule.forRoot(),
        AppRoutingModule,
        StoreModule.provideStore(reducer),
        EffectsModule.run(ProjectEffects)
    ],
    providers: [
        ApiService,
        AuthGuard,
        UnauthGuard
    ],
    bootstrap: [AppComponent]
}
```

**Comment by MikeRyan52** [comment]
See angular/angular-cli#2799

**Comment by glendaviesnz** [comment]
FYI - The latest version of ngc-webpack doesn't appear to have this problem. Just tried the latest build of https://github.com/AngularClass/angular2-webpack-starter which uses this plugin for AoT build and the @Effects appear to work fine in the AoT production build in the quick test I just did.

**Comment by piercers** [comment]
According to [this comment](https://github.com/angular/angular-cli/issues/2799#issuecomment-269373749), decorators should work with Angular CLI and AoT, now?

If so, is this `Invalid provider for the NgModule 'EffectsModule` related? I'm getting this error when trying to build with AoT.

**Comment by brandonroberts** [comment]
Closing as the Angular CLI does not remove decorators as of beta 24.
