### ISSUE TITLE
How to test catch callback?

### ISSUE THREAD

**Issue by prp1** [ngrx/effects#72]
In the documentation it is shown how to test effect if is successfully resolved, but what if it throws error? How to test that?

Here is my effect:

```
@Effect()
public getAnswerApp$: Observable<Action> = this._actions$
    .ofType(BiddingActions.GET_ANSWERING_APP)
    .map(action => action.payload)
    .switchMap(
        ({ eAuctionId, tenderId }) => this._biddingApiService
        .getAnsweringApp(eAuctionId, tenderId))
    .map((response: GetAnsweringAppResponseModel) =>
        this._biddingActions.getAnsweringAppSuccess(response))
    .catch(() => {
        //
        // PROBLEM: HOW TO TEST THIS CATCH CALLBACK?
        //
        this._notificationsService.error('Api error: could not get answer app');
        return Observable.of(this._biddingActions.getAnsweringAppError());
    });
```

And here is my test:

```
describe('BiddingEffects', () => {
    beforeEach(() => TestBed.configureTestingModule({
        imports: [
            EffectsTestingModule,
            HttpModule,
            NotificationsModule,
        ],
        providers: [
            ApiService,
            BiddingEffects,
            BiddingActions,
            BiddingApiService,
        ],
      }));

    let runner: EffectsRunner;
    let biddingEffects: BiddingEffects;
    let biddingActions = new BiddingActions();

    beforeEach(inject([
        EffectsRunner,
        BiddingEffects,
    ], (_runner: EffectsRunner, _biddingEffects: BiddingEffects) => {
        runner = _runner;
        biddingEffects = _biddingEffects;
    }));

    describe('getAnswerApp$', () => {

        it('should return biddingActions.getAnsweringAppSuccess action result', () => {
            const response = {
                data: '<iframe></iframe>',
            };
            runner.queue(biddingActions.getAnsweringApp(1, 1));

            biddingEffects.getAnswerApp$.subscribe((result) => {
                expect(result).toEqual(biddingActions.getAnsweringAppSuccess(response));
            });
        });

    });

});

```

**Comment by chrigu** [comment]
what about 
`
let stream$ = biddingEffects.getAnswerApp$.catch((result) => {/* test code */});
stream$.subscribe(........)
`

@prp1 Just another thing: How did you manage to setup the tests? Did you ever run in a "No provider for Store!" error while testing? I have this all the time and my effect-test won't work.

**Comment by prp1** [comment]
I get a typescript error regarding types when try to implement your solution. But it actually seems to me a bit illogical as I need to cause the error, not to catch it in the test.

Setuping tests worked for me and I didn't have such error. Here is my full code:


`
import { Observable } from 'rxjs/Observable';
import { TranslateModule } from 'ng2-translate';
import { NotificationsModule } from './../../notifications/notifications.module';
import { HttpModule } from '@angular/http';
import { ApiService } from './../../core/shared/api.service';
import { BiddingApiService } from './../shared/bidding-api.service';
import { BiddingActions } from './bidding.actions';
import { BiddingEffects } from './bidding.effects';
import { TestBed, inject } from '@angular/core/testing';
import { EffectsTestingModule, EffectsRunner } from '@ngrx/effects/testing';

describe('BiddingEffects', () => {
    beforeEach(() => TestBed.configureTestingModule({
        imports: [
            EffectsTestingModule,
            HttpModule,
            NotificationsModule,
            TranslateModule.forRoot(),
        ],
        providers: [
            ApiService,
            BiddingEffects,
            BiddingActions,
            BiddingApiService,
        ],
    }));

    let runner: EffectsRunner;
    let biddingEffects: BiddingEffects;
    let biddingActions = new BiddingActions();
    let biddingApiService: BiddingApiService;

    beforeEach(inject([
        EffectsRunner,
        BiddingEffects,
        BiddingApiService,
    ], (a: EffectsRunner, b: BiddingEffects, c: BiddingApiService) => {
        runner = a;
        biddingEffects = b;
        biddingApiService = c;
    }));

    describe('getAnswerApp$', () => {

        it('should return biddingActions.getAnsweringAppSuccess action result', () => {
            const response = {
                data: '<iframe></iframe>',
            };
            spyOn(biddingApiService, 'getAnsweringApp').and.returnValue(Observable.of(response));
            runner.queue(biddingActions.getAnsweringApp(1, 1));

            biddingEffects.getAnswerApp$.subscribe((result) => {
                expect(result).toEqual(biddingActions.getAnsweringAppSuccess(response));
            });
        });

    });

});
`

**Comment by prp1** [comment]
I finally solved this, it was pretty easy actually...  Method, that effect is calling, should throw an error, and then catch callback will be executed.

      
    it('should call NotificationsService.error method if request to api fails', () => {
        spyOn(biddingApiService, 'getAnsweringApp')
             .and.returnValue(Observable.throw('dummy error'));
        spyOn(notificationsService, 'error');
            runner.queue(biddingActions.getAnsweringApp(1, 1));

        biddingEffects.getAnswerApp$.subscribe((result) => {
             expect(notificationsService.error).toHaveBeenCalled();
        });
    });

**Comment by chrigu** [comment]
a sorry, then I misunderstood the whole thing. But it's good to hear that it works for you.

Thanks for providing the whole code, but somehow I still get the error with the Store. I guess I have to dig a bit deeper here.

**Comment by benjackson84** [comment]
@chrigu to "provide" the store in your tests you need to import the storeModule and provide it like:

```
const gameStateSpy = jasmine.createSpy('gameState').and.callFake((state, action) => gameState(state, action));
beforeEach(async(() => {
  TestBed.configureTestingModule({
    declarations: [...],
    providers: [...],
    imports: [ StoreModule.provideStore({ gameState: gameStateSpy }) ]
  })
  .compileComponents();
}));
```

In this example I've also created a spy for the store so I can detect calls to it
