### ISSUE TITLE
intro example AuthEffects injectable implements OnDestroy

### ISSUE THREAD

**Issue by mikkelrd** [ngrx/effects#73]
I don't think the `implements OnDestroy` part of `intro.md` is intentional and should be removed.
1. OnDestroy is not imported in the displayed code
2. Injectables don't have a lifecycle so OnDestroy or OnInit are not used

**Comment by DzmitryShylovich** [comment]
Injecatables **do** have OnDestroy hook.

**Comment by mikkelrd** [comment]
> Angular calls lifecycle hook methods on directives and components as it creates, changes, and destroys them.
https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html

Docs on lifecycle hooks don't mention anything about lifecycle hooks for providers, much less injectables. I believe implementing abstract classes unnecessarily like this just bogs code down.

**Comment by MikeRyan52** [comment]
The `implements OnDestroy` is vestigial from previous versions of @ngrx/effects and needs to be removed. However, @DzmitryShylovich is correct in that providers can implement some lifecycle hooks.

**Comment by mikkelrd** [comment]
Hmm. Interesting. I can't find anything in the docs about that.
