### ISSUE TITLE
Allow ofType to also accept Symbols

### ISSUE THREAD

**Issue by woutderooms** [ngrx/effects#77]
I think it would be a good idea to allow the `ofType` function to accept Symbols.

I was considering moving from string based action types to symbols, to check the performance difference in a full scale application. However I realized the Effects module is not foreseen to compare Symbols, but only strings.

For those unfamiliar with Symbols: https://www.typescriptlang.org/docs/handbook/symbols.html

**Comment by StevenLiekens** [comment]
Does the `Action` interface allow that you assign a symbol to the `type` property? I thought that `type` has to be a string.

**Comment by woutderooms** [comment]
I could use my own Action interface for this without too much trouble, but to get the effects to work I would have to modify the effects library. So I was wondering if there was any intention for doing this. I would assume not.

I think this issue can be closed as it doesn't people are looking for this feature.

**Comment by btrigueiro** [comment]
Our team is looking to have that feature too. Using symbols as a unique action type, instead of 'loose' strings that could easily get duplicated.
Should I go ahead and look into a PR?

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
