### ISSUE TITLE
Duplicate Effects dispatched for Lazily-loaded modules

### ISSUE THREAD

**Issue by exk0730** [ngrx/effects#80]
Angular version: 2.2.1 (or 2.2.3)

**Bug description** If a lazily-loaded module uses `EffectsModule.run(SomeEffects)`, actions that are dispatched from `SomeEffects` will be dispatched twice. If `EffectsModule.run(SomeEffects)` is imported in the root app module, those actions will **not** be dispatched twice.

_Side Note:_ it seems the `replace-reducer` action is not getting logged correctly in store dev tools logger (ngrx/store/init should not have the lazily-loaded state but you can see here 
![screen shot 2016-11-28 at 11 31 44 am](https://cloud.githubusercontent.com/assets/6395698/20676674/879fbbe4-b55e-11e6-9064-b4067b25dac0.png)
 that it does have the "lazy" state)

**Reproduced here**:
https://github.com/exk0730/angular-webpack2-starter/tree/no-universal-support

**Comment by qdouble** [comment]
@exk0730 this is router bug: https://github.com/angular/angular/issues/12869

**Comment by exk0730** [comment]
@qdouble thanks.

**Comment by santialbo** [comment]
@qdouble is there a known workaround to this (even if its hackish)? should be just not user lazy loaded modules? the guys at the angular team don't even seem to care.
