### ISSUE TITLE
effect dispatch twice one action

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/effects#81]
I have a problem with my code https://github.com/wizardnet972/tic-tac-toe
Actions on effects (with switchMap) dispatch more then one time.

[for example](https://github.com/wizardnet972/tic-tac-toe/blob/master/src/client/app/board/board.effects.ts#L31)
when I click the button: new-game then should dispatch 'reset game' action. the effect should catch it and return new action, 'reset_store'. The problem 'reset_store' dispatch twice!

is it a bug? because I just upgrade the package.json and not changing anything in the code...

**Comment by chrissena** [comment]
It's a bug with the latest version of angular router https://github.com/angular/angular/issues/12869. This has already been mentioned https://github.com/ngrx/effects/issues/76 . You can use a previous version of the angular router (2.1.0) while the angular team fix the underlying issue.

**Comment by karolmie1** [comment]
It won't be fixed in months, or maybe it will not be ever fixed. Is there any way to hack a way around it in effects?

**Comment by chrissena** [comment]
If you place the  EffectsModule.run( YourEffectsService ) in the imports list of the root module (AppModule) rather than a lazy loaded module the effects should only run once.

This means you should provide any services that your effects class(es) depend(s) on in the root module also.

**Comment by alexander-heimbuch** [comment]
@chrissena That interferes with the modular approach for lazy loaded components :/ Also struggling with this issue.

**Comment by chrissena** [comment]
@alexander-heimbuch It sure does! 
However I just decided to go ahead and break the encapsulation temporarily for another month or so until angular 4.0 final is released with the bug fix. (Last I heard the eta is mid-April.)

I'm not aware of any hack to maintain the module encapsulation with this bug in the current router so I just reworked my code as a temp fix. My EffectsService only depends on the store and Angular's built in services(e.g. HTTP) so it's not a big deal in my case.

**Comment by chrissena** [comment]
@alexander-heimbuch There's also this hack someone else used. (I have not tried it, so don't know how well it works)
[Overriden EffectsModule and EffectsSubscription to prevent double requests](https://gist.github.com/kel-sakal-biyik/32540198fd0363ea6422992e84c700dc#file-effects-hack-module-ts-L33)
