### ISSUE TITLE
Document the usage of @ngrx/effects for rehydrating state upon application bootstrap

### ISSUE THREAD

**Issue by balteo** [ngrx/effects#82]
It would be nice to have some sample code demonstrating the use of **@ngrx/effects** for rehydrating application state when the application loads/bootstraps.

The only documentation I have found is here: https://gist.github.com/btroncone/a6e4347326749f938510#rehydrating-application-state-on-bootstrap and it does not use **@ngrx/effects**.

Can someone provide a link to a working sample that demonstrates how to use meta reducers that with dependencies (such as angular 2 services)?

The following sample is nice but a little too simplistic insofar as it does not have any dependency.

```
export const RESET_STATE = 'RESET_STATE';

const INIT = '__NOT_A_REAL_ACTION__';

export const reset = reducer => {
    let initialState = reducer(undefined, {type: INIT})
    return function (state, action) {
      //if reset action is fired, return initial state
      if(action.type === RESET_STATE){
        return initialState;
      }
      //calculate next state based on action
      let nextState = reducer(state, action);
      //return nextState as normal when not reset action
      return nextState;
  }
} 

```

business app will often rely on http calls to the backend in order to rehydrate state...

Documentation in that sense would therefore be great!

**Comment by karolmie1** [comment]
I've set something up for angular hmr, but by no means it's the best solution: https://bitbucket.org/kmierzej/fragaria-webapp

```
export function reducer(state: any, action: any) {
    state = globalReducer(state, action);
    if ('production' === ENV) {
        let productionReducer: ActionReducer<IState> = combineReducers(reducers);
        return productionReducer(state, action);
    } else {
        let developmentReducer: ActionReducer<IState> = compose(storeFreeze, combineReducers)(reducers);  // tslint:disable-line:max-line-length
        return developmentReducer(state, action);
    }
}

function globalReducer(state: IState, action: any) {
    switch (action.type) {
        case AppActions.ActionTypes.SET_APP_STATE: {
            let payload = (action as AppActions.SetAppStateAction).payload;
            return payload;
        }
        default: {
            return state;
        }
    }
}
```
One could implement SET_APP_STATE as PATCH_APP_STATE, and that event could be emitted by any service as soon as they fetch data uppon rehydration.

Is this something remotely close to what you want?

**Comment by robwormald** [comment]
See https://github.com/ngrx/platform/issues/101

**Comment by dereklin** [comment]
In ngrx 2, with hmr, I used this code to rehydrate my state in my reducer index.ts: 
```
function stateSetter(myReducer: ActionReducer<any>): ActionReducer<any> {
  return (state, action) => {
    if (action.type === 'SET_ROOT_STATE') {
      return action.payload;
    }
    return myReducer(state, action);
  };
}
```
Now that the reducers is a simple map with ngrx 4, how can I listen to an action and return back a global state in the reducer index.ts?

**Comment by Kaffiend** [comment]
@dereklin just include `stateSetter` in your development metaReducers.

```
export const metaReducers: ActionReducer<any, any>[] = ENV !== 'production'
  ? [stateSetter]
  : [];
```

**Comment by dereklin** [comment]
@Kaffiend Thanks so much!!  It works just like before now :)
