### ISSUE TITLE
Turn effects on/off on demand

### ISSUE THREAD

**Issue by michaelgeorgeattard** [ngrx/effects#84]
We would like some effects to run only when on a specific route. Instead of filtering, I thought it would be better to disable the subscriptions altogether.

Is it possible to turn off effect subscriptions on demand?

**Comment by DzmitryShylovich** [comment]
You can use `filter`

**Comment by spali** [comment]
at least a workaround would be to filter the effect based on a state which indicated the enabled or disabled state.
```
.ofType(...)
.withLatestFrom(this.state$)
.filter(([action, state]) => state.effectEnabled)
.map(([action, state]) => action)
...
```
possible use case I use: I filter out effects if the related state data is still loading from the backend.

**Comment by wizardnet972** [comment]
You can add or remove effect manually using mergeEffects [like this](https://github.com/wizardnet972/memory-game-ngrx/blob/master/src/shared/effects-helper.service.ts).

The idea is to subscribe effect to store or not.

**Comment by AngelaE** [comment]
It works by creating an empty effect subscription as parent, and then creating child-subscriptions with the effects to be turned on/off.

1. create empty EffectsSubscription on start:
```
class FakeEffects {}

const effects = [
  EffectsModule.runAfterBootstrap(FakeEffects)
]
```
2. Ensure all required dependencies are available. Easiest to pass in through DI in the constructor:
```
 constructor(
    @Inject(Store) private store: Observer<Actions>,
    @Optional() @SkipSelf() private parent: EffectsSubscription,
    private effectsInstance1: Effect1) {}
```

3. create instances of the effect classes 

4. Then create a nested subscription with the required effects:
```
this.store.next(<any>clearStoreQueue) //This makes sure no valid action is queued in the store, only important if effects are turned off and then on again
const effects = [effectInstance1, effectInstance1, ...]
 this.nestedSubscription = new EffectsSubscription(this.store, this.parent, effects)
```

5. Unsubscribe from the child subscription if required
```
  clear() {
    if (this.nestedSubscription) {
      this.nestedSubscription.unsubscribe()
      this.nestedSubscription = null
    }
  }
```

6. repeat step 4 to enable the effects again.

(Cannot take credit for this solution, my work mate came up with it. Would be great if this was in the docs.)

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
