### ISSUE TITLE
dispatch in effect class constructor leads to not executed effects.

### ISSUE THREAD

**Issue by spali** [ngrx/effects#85]
As soon as I have more than one effect class which dispatch a load action in the effect class constructor, only one effect is executed.
See plunk: http://plnkr.co/edit/EOy7nAki83HTmbtTxq3Q?p=preview
There are two effect classes `DataEffects` and `Data2Effects`. Both have a dispatch of the load action in the constructor. But only one reaches the success effect.
If I wrap the dispatch in a `setTimeout` (see commented line) it works and both success effects get's executed.
I can reproduce this also if I dispatch the same load action in one of the effect class twice. Only one success effect get's executed.
Probably `@Effect` decorator and the constructor execution order is random and leads to undefined behavior?

**Comment by wizardnet972** [comment]
@spali you should not use in effect contractor to dispatch action. this is not what ngrx like :)

to do that use `startWith` operator.

This is the fix for data2. use same fix to data1:

```
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/do';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/startWith';
import { Injectable } from '@angular/core';

import { Actions, Effect } from '@ngrx/effects';

import { Data2Actions } from '../actions/data2';
import { Data2Service } from '../services/data2';

import { Store } from '@ngrx/store';
import { AppState } from '../reducers/index';

@Injectable()
export class Data2Effects {
  constructor(
    private actions$: Actions,
    private data: Data2Service,
    private dataActions: Data2Actions,
    private store: Store<AppState>
  ) {
   // this.store.dispatch(this.dataActions.load()); // one of data and data2 effects does not work
    //setTimeout(() => this.store.dispatch(this.dataActions.load())); // works
  }

  @Effect()
  load$ = this.actions$.ofType(Data2Actions.LOAD)
    .startWith(Data2Actions.LOAD)
    .map(action => action.payload)
    .mergeMap(data =>
      this.data.load()
        .map(data => this.dataActions.loadSuccess(data))
    );

}

```

**Comment by spali** [comment]
Thanks for the feedback. Yes I had used it with `startWith` but I wanted to make it configurable what effects will be fired initially to make my caching configurable (define which data will be loaded at startup).
I thought the effect constructor would be the perfect place for this :)
But I can put this in an separate service to handle it centrally for all effects and dispatch there.

@MikeRyan52  You can close the Issue if you don't want to investigate more into this.
