### ISSUE TITLE
Effect not getting called after an error

### ISSUE THREAD

**Issue by ramachandrann** [ngrx/effects#89]
Hello ,

To keep clutter away, I haven't shown the complete Effect class.  When I dispatch the SAVE_TODO_INFO action, the effect gets called and if todoService success everything goes fine but if the todoService fails and catch() block gets executed, the next call to save the same data is NOT calling the effect at all.

  @Effect()
  search$: Observable<Action> = this.actions$
    .ofType(todoActions.ToDoActionTypes.SAVE_TODO_INFO)
    .map((action: todoActions.SaveToDoAction) => action.payload)
    .switchMap((data: TodoInfo) => {
      return this.todoService.saveToDoInfo(data)      
    })
    .map((data: any) => new todoActions.TodoInfoSavedAction(data))
    .catch((error) => {
      console.debug('HTTP Response', error);
      return of(new todoActions.SaveTodoInfoFailAction(error._body))
    });

package json dependencies
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/router-store": "^1.2.5",
    "@ngrx/store": "^2.2.1",
    "@ngrx/store-devtools": "^3.2.2",
    "core-js": "^2.4.1",
    "ngrx-store-freeze": "^0.1.6",
    "reselect": "^2.5.4",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },

Can you pls help?

Thanks
Gopal

**Comment by brandonroberts** [comment]
Your catch should be chained to your `saveToDoInfo` request and not chained to the effect

**Comment by nfantone** [comment]
@brandonroberts Apologies for resurrecting a closed issue, but what about cases like [this one](https://github.com/ngrx/effects/issues/112#issuecomment-299869758)? What if you need to continue executing actions after your service call, but want to interrupt the stream if anything (anywhere) goes wrong? This would behave like a batch set of actions that could all either fail or succeed together and have no place functioning alone/separately.
