### ISSUE TITLE
Question: Effects and server side form validation

### ISSUE THREAD

**Issue by ssljivic** [ngrx/effects#90]
Could some one please provide an example or explain the concept on how effects should handle server side form validation errors?

**Comment by abdulhaq-e** [comment]
1- An `Action` activates the `Effect`. For example `FormSubmitInitAction` causes the `formSumbitInitEffect` to run.
2- Inside the effect a request is sent to the server.
3- For a successful  request, the results of these requests are mapped to a new action, e.g. `FormSubmitSuccessAction`.
4- For a failed request, the errors return from the server are mapped to a new action, e.g. `FormSubmitFailAction`

Both actions would then activate a reducer which should update the store with the results of the request whether it was an error or not.

**Comment by ssljivic** [comment]
That is what I also had in mind, but it seems like an overkill to store the validation errors in the state. The validation errors are not something that belongs to the "long term" state. 

Any other ideas?

Also, if we keep server side validation errors in the state, then it seems logical to keep client side validation errors in the sate as well, so how can we achieve that?

**Comment by ssljivic** [comment]
Further it seem that we will also need an action and reducer to ClearFormErrors once we start editing new item so that we do not see the errors of a previous item edit session. All this seems like a big overhead.

**Comment by abdulhaq-e** [comment]
I am looking at this more. The good thing about ngrx is that there is a huge amount of `redux` experience available. Ideas and thoughts can be brought to the ngrx world. I'm currently seeing how `redux form` work http://redux-form.com/6.4.3/

**Comment by fxck** [comment]
Yes, this problem and many others would be solved with ngrx/forms, it's something I'd really like to see, did some experiments already, but I'm really waiting for Mike to chat about it, also to get others on board. What I tested was building it on top of angular forms, but I don't think it's a way to go, but it definitely should support angular value accessors, which would make it compatible with any component utilizing angular forms.

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
