### ISSUE TITLE
How do cache api requests?

### ISSUE THREAD

**Issue by seescode** [ngrx/effects#91]
I'm not sure how to cache api responses using ngrx effects.  I was studying this code which handles caching api responses:

https://github.com/btroncone/ngrx-examples/blob/master/async/src/app/effects/reddit-effects.ts

But this is using an outdated version of ngrx effects.  In the older version whenAction() exposed the state and action.  ofType() as far as I can tell only exposes action.  I can't check the state object to see if the data is already cached or not.  

Thanks for any guidance you can provide!

**Comment by littleStudent** [comment]
you can still get the state like this I guess.

```Javascript
actions$
  .ofType('login')
  .withLatestFrom(store$)
  .map(([ action, state ]) => ({ action, state }))
```

**Comment by seescode** [comment]
Yep, this worked for me.  Thanks!

**Comment by ArielGueta** [comment]
The problem here is that the login action already sets the pending key on the state to true and if your data is cached your spinner is stuck.
