### ISSUE TITLE
Use updated state in effect

### ISSUE THREAD

**Issue by cmckni3** [ngrx/effects#92]
I am having an issue where my action is receiving the payload that was dispatched. I want to new state after my reducer has processed the state change.

Is this possible? Do I need to dispatch another action, `MY_ACTION_SUCCESS`, with the new payload?

**Comment by brandonroberts** [comment]
If you need to get the latest from state, you use the `withLatestFrom` operator with the effect to get the current state or slice of state you need

**Comment by cmckni3** [comment]
Thanks @brandonroberts! I used #49 as a reference.

**Comment by cormacrelf** [comment]
FYI, `actions$.withLatestFrom(state$)` in general gives you the copy of state from just prior to the action being fired.

You can make it wait till after by adding a `.delay(0)` in between, so the effect is processed on the next tick (i.e. straight after the reducer runs / the UI updates). This is the classic `setTimeout(function, 0)` trick updated for RxJS.

```typescript
@Effect() withAfterState$ = this.actions$
    .ofType("XXX")
    .delay(0)
    .withLatestFrom(this.store.select(...), (action, state) => { return ...; })
```
