### ISSUE TITLE
Multiple effects only trigger one reducer

### ISSUE THREAD

**Issue by tonychangcheng** [ngrx/effects#93]
Take the https://github.com/ngrx/example-app for example. 

If I do multiple times dispatch. e.g. 3 times just for an experiment 
    this.store.dispatch(new book.SearchAction('a'));
    this.store.dispatch(new book.SearchAction('c'));
    this.store.dispatch(new book.SearchAction('d'));

The BookEffects.search$ (the below return) will be triggered 3 times which is correct. 
return this.googleBooks.searchBooks(query)
        .takeUntil(nextSearch$)
        .map(books => new book.SearchCompleteAction(books))
        .catch(() => of(new book.SearchCompleteAction([])));

But the reducer search book.ActionTypes.SEARCH_COMPLETE would only be triggered once by the last time effect('d' action).

Is this the right behaviour of ngrx? How can I let the reducer to fire 3 times? I mean letting the reducer to update every time when effects return.

**Comment by bertofer** [comment]
Can you provide the complete BookEffects.search$ definition? (With the ofType and everything).

I'm guessing that if this return is inside a map, could you try a flatMap instead?

**Comment by tonychangcheng** [comment]
I am using the https://github.com/ngrx/example-app for example where you can see all the code.

The only change is to do multiple times dispatch as below.
this.store.dispatch(new book.SearchAction('a'));
this.store.dispatch(new book.SearchAction('c'));
this.store.dispatch(new book.SearchAction('d'));

I expect the reducer search book.ActionTypes.SEARCH_COMPLETE to be triggered 3 times. But it was only triggered just one time.

**Comment by ciesielskico** [comment]
I have the same problem.

I'm reading an array of objects to be sent to the server from localStorage.

My actions look like this:

```
1. READ_LOCALSTORAGE
2. READ_LOCALSTORAGE_SUCCESS
```

and on the returned array I do:

`array.forEach(obj => this.store.dispatch(new SendAction(obj));`

I can see 3 `SEND_ACTIONS` in the console, but only one `SEND_SUCCESS` (the last one).

**Comment by MJuma** [comment]
@ciesielskico Replace your switchMap with a mergeMap.

**Comment by tonychangcheng** [comment]
@MJuma Thanks. It works for me.
