### ISSUE TITLE
Weird behavior difference between switchMap / switchMapTo operators inside an effect.

### ISSUE THREAD

**Issue by bertrandg** [ngrx/effects#94]
I think my problem/misunderstanding is more related to rxjs but I post it here first because I got it using `ngrx/store` + `ngrx/effects`..

I made a simple plunker to illustrate it:
https://plnkr.co/edit/5ht12T?p=preview

I have 2 buttons triggering 2 actions `ACTION_1_LOAD`/`ACTION_2_LOAD`.
Both triggered a specific effect calling an http request using `@angular/http`.
If request works, it triggered actions `ACTION_1_SUCCESS`/`ACTION_2_SUCCESS`
Otherwise actions `ACTION_1_FAIL`/`ACTION_2_FAIL`

Only difference between them: 
- I used `switchMapTo` inside `ACTION_1_LOAD` effect.
- I used `switchMap` inside `ACTION_2_LOAD` effect.

You can see in your console that using `switchMapTo`, my `request` method is called at app initialisation and never again.
In contrary, with `switchMap`, my `request` method is not called at initialisation but each time `ACTION_2_LOAD` is triggered.

Is that a bug for you or do you have any explanations about it?

And big thanks for this great redux implementation, that's a real pleasure to work with! :+1:

**Comment by mike-park** [comment]
Seems like it works as expected to me. 

`switchMapTo` evaluates the parameter when the effects.js file is evaluated. ie the call to posts/1 happens when effects.js is parsed.

`switchMap` evaluates the parameter function only when an observable is proceeding down the pipeline, hence only after an `ACTION_2_LOAD` event.

**Comment by bertrandg** [comment]
@mike-park 
With `switchMapTo` the request method (with the log) is called when the `effects.js` file is evaluated **but** the http call is done only on `ACTION_1_LOAD`.

This is what makes me troubles because I use a custom `Http` which add JWT auth token to headers. 
And using `switchMapTo`, all request are sent with a null token because user is not identified yet at app initialisation.

But that's ok if you say it's the normal behavior because `switchMap` do the job I need. 
It's just that with names almost the same, I was presuming they worked the same way..

**Comment by bertrandg** [comment]
Nobody else to confirm me this behavior before closing the issue?

**Comment by karolmie1** [comment]
@mike-park Not, really, call to post/1 still happens after every button click, it's just that request function is called once, caused by reasons you've explained. You can see that, if you peek at the steam using: 

`.map(x => {console.log('peek-a-boo'); return x;})`

Still not a bug, and even if it was it would be rxjs fault.

**Comment by karolmie1** [comment]
Do you need any more information? Can you close the issue?

**Comment by vaclav-antosik** [comment]
I'm experiencing same behavior - inner observable is triggered even if there is no "item" in outer observable. So inner observables are activated immediately at app initialization. 

I consider this behavior as a bug.

**Comment by bertrandg** [comment]
I totally agree it's related to rxjs and discovered that this is the normal behavior even if it doesn't sound really natural..

I found a stackoverflow issue explaining it clearly:
https://stackoverflow.com/questions/39108549/switchmapto-creates-observable-before-subscription

I close the issue.

**Comment by bertrandg** [comment]
Thanks @mike-park  & @karolmie1 ! :)
