### ISSUE TITLE
web workers

### ISSUE THREAD

**Issue by CoderCat84** [ngrx/effects#95]
Just wanted to throw a thought out there, has it ever been considered to run ngrx/effects on a web worker?    It seems like pretty prime case for it given that it subscribes to messages and responds with a message and doesn't access the DOM.  There would obviously be some challenges like getting the latest state from the store but I feel like; at least in the way that I use ngrx this might work well, my reducers are pure and simple my views only subscribe to observable from the store and my effects do all of the heavy lifting.

**Comment by robwormald** [comment]
Hi CoderCat84 - we're migrating over to https://github.com/ngrx/platform - so I've re-opened this over here https://github.com/ngrx/platform/issues/102 - FWIW, i think this is an excellent idea and it's something I'd love to pursue 👍
