### ISSUE TITLE
Question on how to extend BaseEffects

### ISSUE THREAD

**Issue by JonnyBGod** [ngrx/effects#98]
Hi all and thanks in advance,

I am trying to create a ```BaseEffects``` Class and then a bunch of other classes that extend base.

Current implementation:

base.ts
```
@Injectable()
export class BaseLoopbackEffects {
  public upperName: string;

  @Effect()
  public create: Observable<Action> = this.actions$
    .ofType(this.actionTypes[this.upperName + '_CREATE'])
    .map(toPayload)
    .mergeMap((payload) =>
      this.apiService.create(payload)
        .map((response) => new this.actionTypes.loginSuccess(response))
        .catch((error) => concat(of(new this.actionTypes.loginFail(error)), of(new LoopbackErrorActions.error(error))))
    );

  @Effect()
  public test: Observable<Action> = this.actions$
    .ofType(UserActionTypes.USER_CREATE_SUCCESS)
    .map((action) => new LoopbackErrorActions.error(action.payload));

  constructor(
    public actions$: Actions,
    public apiService: any,
    public modelName: string,
    public actionTypes: any
  ) {
    this.upperName = modelName.toUpperCase();
  }
};
```

user.ts
```
@Injectable()
export class UserEffects extends BaseLoopbackEffects {
  @Effect()
  public login: Observable<Action> = this.actions$
    .ofType(UserActionTypes.LOGIN)
    .map(toPayload)
    .mergeMap((payload) =>
      this.user.login(payload.credentials, payload.include, payload.rememberMe)
        .map((response) => new UserActions.loginSuccess(response))
        .catch((error) => concat(of(new UserActions.loginFail(error)), of(new LoopbackErrorActions.error(error))))
    );

  @Effect()
  public logout: Observable<Action> = this.actions$
    .ofType(UserActionTypes.LOGOUT)
    .map(toPayload)
    .mergeMap((payload) =>
      this.user.logout()
        .map(() => new UserActions.logoutSuccess())
        .catch((error) => concat(of(new UserActions.logoutFail()), of(new LoopbackErrorActions.error(error))))
    );

  constructor(
    @Inject(Actions) public actions$: Actions,
    @Inject(UserApi) public user: UserApi
  ) {
    super(actions$, user, 'User', UserActionTypes);
  }
}
```

Problem is that this apparently is not working.
```UserEffects``` effects work properly but ```BaseLoopbackEffects``` are not triggered.

Any idea of why this is not working?

**Comment by JonnyBGod** [comment]
@spali I read in another issue that you have accomplished this. Can you give me some insight on how did you do it?

**Comment by spali** [comment]
It's a bit uggly, but I started with a base class just as a you would do an effect class by default. Only difference, no `@Effect` decorator. then extend this class and just redeclare the effect properties without assigning a value and add the `@Effect` decorator.

Example:
```
class BaseEffect {
 protected myEffect = ....

 ...
}

class SubEffect extends BaseEffect {
 @Effect()
 protected myEffect;

 ...
}
```

If you inject something you need to inject it in the sub-class and manually invoke the super constructor of the BaseEffect class.

But currently I ended implementing all Effects in a effect "utility" class and assign the effects in the real effect class.
This allows me to reuse the same effect mutliple times and specific operators as needed during the assignement. I.e. I have a base-util class which all my Model Item uses. And I have an selection-util class which all model items can use that support selection.

```
class MyEffectUtil {
  public myEffect = ....

  ....
}

class MyEffects {

 protected myEffect = myEffectUtil.myEffect;

 constructor(protected myEffectUtil: MyEffectUtil) {}
}

**Comment by altschuler** [comment]
@spali Where do you decorate the effects? In the `MyEffectUtil` or do you 'import' it in your concrete effect classes and decorate there? I can't tell from your last sample, but it looks interesting :)

**Comment by spali** [comment]
In the concrete effect class because this allows reusing the effect logic of the util class in multiple variations in the concrete effect classes.

**Comment by altschuler** [comment]
Makes sense, thanks!

**Comment by jonesmac** [comment]
I also ran into this and found an interesting solution similar to @spali.  You can decorate methods in the derived class that return methods in the base class (which are undecorated).

``` javascript
constructor(
    actions$: Actions,
    apiService: ApiService,
    store: Store<any>,
    model: Model
  ) {
    super('SomeActionString', 'SomeReducerKey', actions$, apiService, store, model);
    // Effects cannot be run from base classes :(
    // If we use the decorators here, we can return
    // the actual methods in the base class which are
    // then registered in the store
    this.initCreate();
  }

  @Effect()
  initCreate() {
    return this.create();
  }
```

then in the base class...
``` javascript
  create(): Observable<Action> {
    let CREATE = 'CREATE_' + this.ACTION_TYPE;
    return this.actions$
            .ofType(CREATE)
            .map(action => action.payload)
            .switchMap(payload => this.api.create(payload)
              .map(res => {
                return { type: `RECEIVE_${this.ACTION_TYPE}`, payload: res };
              })
              .catch(e => Observable.of({ type: `FAILED_FETCH_${this.ACTION_TYPE}`, payload: e }))
            );
  }
```

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!

**Comment by vidakovic** [comment]
@robwormald I'm still having this issue with v4. As a workaround I've used @spali 's suggestion (no decorators in base class and re-define variables with decorators)
