### ISSUE TITLE
AOT build fails with angular 4.0.0-beta.4

### ISSUE THREAD

**Issue by guojenman** [ngrx/effects#99]
AOT fails with angular 4 beta 4. Works with latest stable build of 2.4.5, so not 100% if it's a bug yet.

Anyway, the error I'm getting with angular 4 beta 4 is:

```
ERROR in [at-loader] _aot/app/node_modules/@ngrx/effects/src/effects.module.ngfactory.ts:35:67 
    Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
  Types of property 'next' are incompatible.
    Type '(action: Action) => void' is not assignable to type '(value: Actions) => void'.
      Types of parameters 'action' and 'value' are incompatible.
        Type 'Actions' is not assignable to type 'Action'.
          Property 'type' is missing in type 'Actions'.
```

A minimum reproducible app attached below, though there's nothing special about it... just the standard increment/decrement example but with a timeout for the effects.

[campaigns.zip](https://github.com/ngrx/effects/files/742349/campaigns.zip)

**Comment by guojenman** [comment]
No longer an issue with angular 4.0.0-beta.7

**Comment by karolmie1** [comment]
issue with rc2 again? Or maybe just me?

Error at manage-users-effects.module.ngfactory.ts:87:68: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.

**Comment by guojenman** [comment]
@karolmie1  I'm on angular 4-rc2 & effects 2.0.0 and everything works as before.

**Comment by karolmie1** [comment]
@guojenman Maybe your minimal example is too minimal? In case you would like to reproduce: 
https://bitbucket.org/kmierzej/fragaria-webapp/branch/effects-angular4-issue99
You build with: yarn build:prod.

> ERROR in [at-loader] compiled/node_modules/@ngrx/effects/src/effects.module.ngfactory.ts:33:67 
>     TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
>   Types of property 'next' are incompatible.
>     Type '(action: Action) => void' is not assignable to type '(value: Actions) => void'.
>       Types of parameters 'action' and 'value' are incompatible.
>         Type 'Actions' is not assignable to type 'Action'.
>           Property 'type' is missing in type 'Actions'.
> 
> ERROR in [at-loader] compiled/src/app/auth/token-services/token-services.module.ngfactory.ts:61:69 
>     TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
> 
> ERROR in [at-loader] compiled/src/app/prompt/login/login.module.ngfactory.ts:312:69 
>     TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
> 
> ERROR in [at-loader] compiled/src/app/prompt/prompt.module.ngfactory.ts:324:69 
>     TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
> 
> ERROR in [at-loader] compiled/src/app/view/manage-users/manage-users-effects.module.ngfactory.ts:87:68 
>     TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
> 
> ERROR in [at-loader] compiled/src/app/view/settings/settings-effects.module.ngfactory.ts:87:68 
>     TS2345: Argument of type 'Store<any>' is not assignable to parameter of type 'Observer<Actions>'.
>

**Comment by guojenman** [comment]
@karolmie1 the minimal example was just to illustrate the problem I was having w/ beta 4. My actual app is 20k+ lines of code and growing. Though I only have 2 effects classes which totals to around 400 lines of code.

**Comment by guojenman** [comment]
@karolmie1 not at all. i cloned your repo and do see the error, though at a glance, I dont see anything terribly different from my build, except for config and build tools. I'd need to take a closer look but don't have the time at the moment.

**Comment by nosachamos** [comment]
I am facing the same issue with Angular 4.0.0 RC2, I think this has nothing to do with angular, this has to do with upgrading TS.

**Comment by karolmie1** [comment]
Related: https://github.com/ngrx/effects/issues/106
